Repository ocaml/opam, pull requests merged in 2020-12, with the labels that each got.

#4298 Update opam-format to opam-file-format new type definition
  .travis-ci.sh
  .travis.yml
  appveyor.yml
  appveyor_test.sh
  master_changes.md
  opam-format.opam
  src/client/opamAction.ml
  src/client/opamArg.ml
  src/client/opamCliMain.ml
  src/client/opamConfigCommand.ml
  src/client/opamListCommand.ml
  src/client/opamListCommand.mli
  src/format/opamFile.ml
  src/format/opamFile.mli
  src/format/opamFilter.ml
  src/format/opamFormat.ml
  src/format/opamFormat.mli
  src/format/opamFormula.ml
  src/format/opamFormula.mli
  src/format/opamPp.ml
  src/format/opamPp.mli
  src/format/opamTypes.mli
  src/format/opamTypesBase.ml
  src/format/opamTypesBase.mli
  src/solver/opamCudf.ml
  src/state/opamEnv.ml
  src/state/opamFileTools.ml
  src/state/opamPinned.ml
  src/state/opamSwitchState.ml
  src_ext/Makefile.packages
  src_ext/Makefile.sources
  src_ext/patches/opam-file-format/opam-file-format.2.1.1.patch
Labels: PR: QUEUED

#4456 doc/Distributions: Updates regarding nicoo
  doc/pages/Distribution.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#4460 doc: specify url syntax in opam pin usage
  doc/pages/Usage.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#4463 Github actions: linux & macos
  .github/scripts/hygiene.sh
  .github/scripts/main.sh
  .github/scripts/ocaml-cache.sh
  .github/scripts/opam-bs-cache.sh
  .github/scripts/preamble.sh
  .github/workflows/ci.yml
Labels: AREA:TEST

#4428 Var option: fix, test, update
  doc/pages/Manual.md
  doc/pages/Packaging.md
  master_changes.md
  src/client/opamConfigCommand.ml
  src/state/shellscripts/complete.sh
  src/state/shellscripts/complete.zsh
  tests/reftests/var-option.test
Labels: AREA:TEST, KIND: BUG

#4467 Update github actions
  .github/scripts/main.sh
  .github/scripts/preamble.sh
  .github/workflows/ci.yml
  README.md
  master_changes.md
  src/client/opamAuxCommands.ml
  src/client/opamPinCommand.ml
  src/core/opamCached.ml
  tests/patcher.ml
  tests/reftests.ml
  tests/reftests/camelus.test
  tests/reftests/show.test
  tests/reftests/upgrade-format.test
Labels: AREA:TEST

#4385 Cli versioning
  Makefile
  master_changes.md
  src/client/opamAdminCommand.ml
  src/client/opamArg.ml
  src/client/opamArg.mli
  src/client/opamCLIVersion.ml
  src/client/opamCLIVersion.mli
  src/client/opamCommands.ml
  src/client/opamCommands.mli
  tests/reftests/cli-versioning.test
Labels: AREA: UI

#4475 Fix MacOS upgrade CI test using OS-specific opam 1.2 cache
  .github/scripts/main.sh
  .github/workflows/ci.yml
  master_changes.md
Labels: AREA:TEST

#4476 action: run switch pre/post session hooks
  master_changes.md
  src/client/opamSolution.ml
Labels: KIND: BUG
