Repository ocaml/opam, pull requests merged in 2020-09, with the labels that each got.

#4366 Urlpin format upgrade
  master_changes.md
  src/client/opamPinCommand.ml
Labels: KIND: BUG

#4367 Pin show
  master_changes.md
  src/client/opamPinCommand.ml
Labels: AREA: UI, KIND: BUG

#4370 Fix Init sandbox check
  master_changes.md
  src/client/opamAuxCommands.ml
  src/state/shellscripts/bwrap.sh
  src/state/shellscripts/sandbox_exec.sh
Labels: KIND: BUG

#4371 Update opam files
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: AREA: BUILD
