Repository ocaml/opam, pull requests merged in 2020-08, with the labels that each got.

#4240 Add an optional solver relying on opam-0install-cudf
  master_changes.md
  opam-solver.opam
  src/solver/dune
  src/solver/opamBuiltin0install.ml.dummy
  src/solver/opamBuiltin0install.ml.real
  src/solver/opamBuiltin0install.mli
  src/solver/opamCudf.ml
  src/solver/opamCudfSolver.ml
Labels: AREA: SOLVER

#4294 Move src_ext Dune forwards to 2.6.2
  .gitignore
  Makefile
  Makefile.config.in
  configure
  configure.ac
  master_changes.md
  shell/bootstrap-ocaml.sh
  src_ext/Makefile
  src_ext/Makefile.packages
  src_ext/Makefile.sources
Labels: AREA: BUILD

#4304 Distrib page: add repology badges
  doc/pages/Distribution.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#4319 Support -d for opam lock
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: UI, KIND: BUG

#4322 Fix --columns advertised options
  master_changes.md
  src/client/opamArg.ml
  src/client/opamListCommand.ml
  src/client/opamListCommand.mli
Labels: AREA: UI, KIND: BUG

#4324 Consistently have -n as alias of --no-action
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: UI

#4317 CLI help updates
  master_changes.md
  src/client/opamAdminCommand.ml
  src/client/opamArg.ml
  src/client/opamCommands.ml
Labels: AREA: UI, KIND: BUG

#4326 Handle empty environment variable updates
  src/format/opamFile.ml
  src/format/opamLineLexer.mll
Labels: AREA: ENGINE, KIND: BUG

#4316 Implement CLI versioning
  doc/index.html
  doc/pages/FAQ.md
  doc/pages/Usage.md
  master_changes.md
  src/client/opamAdminCommand.ml
  src/client/opamAdminCommand.mli
  src/client/opamArg.ml
  src/client/opamArg.mli
  src/client/opamCLIVersion.ml
  src/client/opamCLIVersion.mli
  src/client/opamClientConfig.ml
  src/client/opamClientConfig.mli
  src/client/opamCommands.ml
  src/client/opamCommands.mli
  src/client/opamMain.ml
  src/core/opamCompat.ml
  src/core/opamCompat.mli
  src/core/opamConsole.ml
  src/core/opamConsole.mli
  src/core/opamCoreConfig.ml
  src/core/opamCoreConfig.mli
  src/core/opamStd.mli
  src/core/opamSystem.ml
  src/core/opamVersion.ml
  src/state/opamGlobalState.ml
  src/state/opamRepositoryState.ml
  src/state/opamStateConfig.ml
  src/state/opamStateConfig.mli
  src/state/opamStateTypes.mli
  src/state/opamSwitchState.ml
Labels: AREA: UI, PR: WIP
