Repository ocaml/opam, pull requests merged in 2021-02, with the labels that each got.

#4517 Update the dependency constraints
  master_changes.md
  opam-client.opam
  opam-solver.opam
Labels: AREA: BUILD

#4497 Restrict to opam-file-format 2.1.2
  .github/workflows/ci.yml
  .travis.yml
  appveyor.yml
  master_changes.md
  opam-format.opam
  src_ext/Makefile.sources
  src_ext/dune-opam-file-format-src
  src_ext/patches/opam-file-format/opam-file-format.2.1.1.patch
Labels: AREA: BUILD

#4535 Fix the conflict with the environment variable name used by dune
  master_changes.md
  src/state/shellscripts/bwrap.sh
  src/state/shellscripts/sandbox_exec.sh
Labels: KIND: BUG

#4550 lint: W59 & E60 handles conf flag fix
  master_changes.md
  src/state/opamFileTools.ml
Labels: KIND: BUG

#4527 Rename hidden-version to avoid-version
  master_changes.md
  src/client/opamClient.ml
  src/format/opamFile.ml
  src/format/opamTypes.mli
  src/format/opamTypesBase.ml
  src/solver/opamBuiltinMccs.ml.real
  src/solver/opamBuiltinZ3.ml.real
  src/solver/opamCudfSolver.ml
  src/solver/opamSolver.ml
  src/state/opamSwitchState.ml
Labels: PR: QUEUED

#4560 [CI] Complete migration from Travis to GitHub Actions
  .travis-ci.sh
  .travis.yml
Labels: AREA:TEST, PR: QUEUED
