Repository ocaml/opam, pull requests merged in 2021-01, with the labels that each got.

#4482 init: fix non-existing file check in csh
  master_changes.md
  src/state/opamEnv.ml
Labels: PR: NEEDS UPDATE

#4508 Fix `features' field parser
  master_changes.md
  src/format/opamFile.ml
Labels: KIND: BUG

#4496 Document the default build environment variables
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#4500 Fix opam-devel's tests on platforms without openssl, GNU-diff and a system-wide ocaml
  master_changes.md
  opam-devel.opam
  tests/Makefile
  tests/bin/dune
  tests/dune
Labels: AREA: BUILD

#4506 Mention pre-built opam for Arm Macs in INSTALL.md
  doc/pages/Install.md
  master_changes.md
Labels: AREA: DOCUMENTATION
