Repository ocaml/opam, pull requests merged in 2021-06, with the labels that each got.

#4687 var: display package hash
  master_changes.md
  src/client/opamCommands.ml
  src/format/opamPath.ml
  src/format/opamPath.mli
  src/state/opamPackageVar.ml
  tests/reftests/var-option.test
Labels: KIND: BUG

#4671 Some clarifications about depexts
  doc/pages/Manual.md
  master_changes.md
  src/state/opamSwitchState.ml
Labels: AREA: DOCUMENTATION

#4679 Display a message on CentOS if EPEL isn't enabled and depexts aren't available
  master_changes.md
  src/client/opamClient.ml
  src/client/opamSolution.ml
  src/solver/opamCudf.ml
  src/solver/opamCudf.mli
  src/state/opamSwitchState.ml
  src/state/opamSwitchState.mli
  src/state/opamSysInteract.ml
  src/state/opamSysInteract.mli
Labels: PR: QUEUED

#4702 Some build fixes
  Makefile
  doc/pages/Install.md
  master_changes.md
  opam-devel.opam
  shell/bootstrap-ocaml.sh
  tests/reftests/dune
  tests/reftests/dune.inc
  tests/reftests/gen.ml
Labels: AREA: BUILD, KIND: BUG

#4710 Fix VT100 support (again)
  master_changes.md
  src/core/opamConsole.ml
Labels: KIND: BUG

#4720 Fix `OPAMZ3DEBUG` cyclic dependency
  .github/scripts/ocaml-cache.sh
  .github/scripts/preamble.sh
  .github/scripts/solvers.sh
  .github/workflows/ci.yml
  CHANGES
  src/client/opamArg.ml
  src/solver/opamBuiltinZ3.ml.real
  src/solver/opamSolverConfig.ml
  src/solver/opamSolverConfig.mli
Labels: KIND: BUG

#4715 Format upgrade fix: remove missing switches from config file
  CHANGES
  src/format/opamFile.ml
  src/state/opamFormatUpgrade.ml
  src/state/opamGlobalState.ml
  src/state/opamStateConfig.ml
  src/state/opamStateConfig.mli
  tests/reftests/dune
  tests/reftests/opamroot-versions.test
  tests/reftests/run.ml
Labels: KIND: BUG

#4723 Z3 compile fix & tests
  .github/scripts/ocaml-cache.sh
  .github/scripts/preamble.sh
  .github/scripts/solvers.sh
  .github/workflows/ci.yml
  master_changes.md
  src/client/opamArg.ml
  src/solver/opamBuiltinZ3.ml.real
  src/solver/opamSolverConfig.ml
  src/solver/opamSolverConfig.mli
Labels: KIND: BUG

#4735 Set DEBIAN_FRONTEND=noninteractive for unsafe-yes
  master_changes.md
  src/state/opamSysInteract.ml
Labels: KIND: BUG
