Repository ocaml/opam, pull requests merged in 2021-11, with the labels that each got.

#4884 git: disable colored output
  master_changes.md
  src/repository/opamGit.ml
Labels: KIND: BUG

#4899 repo: don't display global message when `this-switch' is given
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: UI

#4878 Refactor the Z3 solver backend
  master_changes.md
  src/core/opamConsole.ml
  src/solver/opamBuiltinZ3.real.ml
  src/solver/opamCudf.ml
  src/solver/opamSolver.ml
  src/solver/opamSolverConfig.ml
Labels: AREA: SOLVER

#4863 Document custom licenses
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION
