Repository ocaml/opam, pull requests merged in 2021-05, with the labels that each got.

#4655 Clearer warnings and messages about --cli / OPAMCLI
  master_changes.md
  src/client/opamArg.ml
  src/client/opamCliMain.ml
Labels: AREA: DOCUMENTATION

#4675 Fix typo in switch creation docs
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: DOCUMENTATION, KIND: BUG

#4665 Build release tags as release tarballs
  master_changes.md
  src/client/dune
  src/client/opamCommands.ml
  src/core/opamVersion.ml
  src/core/opamVersion.mli
  src/state/opamFormatUpgrade.ml
Labels: KIND: BUG

#4666 Build release tags as release tarballs [2.0 version]
  .github/scripts/main.sh
  src/client/dune
Labels: KIND: BUG

#4685 Fix `switch` global variable resolving
  master_changes.md
  src/state/opamPackageVar.ml
  tests/reftests/var-option.test
Labels: KIND: BUG

#4667 Fix installation order when processing .install files
  master_changes.md
  src/client/opamAction.ml
  src/core/opamSystem.ml
  tests/reftests/dot-install.test
Labels: KIND: BUG

#4681 Some doc updates
  README.md
  doc/pages/Install.md
  doc/release/readme.md
  master_changes.md
  release/readme.md
Labels: AREA: DOCUMENTATION
