Repository ocaml/opam, pull requests merged in 2021-03, with the labels that each got.

#4570 config report: fix not found and compilers variables display
  master_changes.md
  src/client/opamCommands.ml
Labels: KIND: BUG

#4569 Rebuild "base" packages on changes
  master_changes.md
  src/state/opamSwitchState.ml
Labels: KIND: BUG

#4571 Don't confirm pinning invariant packages
  master_changes.md
  src/client/opamPinCommand.ml
Labels: AREA: UI

#4593 Fix CI configure check
  .github/scripts/hygiene.sh
  .github/scripts/preamble.sh
  master_changes.md
Labels: AREA:TEST

#4513 Doc: manual - remove useless span tag
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION, PR: WIP

#4609 MacOS sandbox: fix realpath use
  master_changes.md
  src/state/shellscripts/sandbox_exec.sh
Labels: KIND: BUG

#4580 pin version: don't error if archive opam file is malformed
  master_changes.md
  src/client/opamAction.ml
Labels: KIND: BUG
