Repository ocaml/opam, pull requests merged in 2021-12, with the labels that each got.

#4927 bootstrap: update ocaml version
  .github/workflows/main.yml
  appveyor.yml
  master_changes.md
  src_ext/Makefile
Labels: AREA: BUILD

#4965 Fix admin repo upgrade internal error
  master_changes.md
  src/client/opamAdminRepoUpgrade.ml
Labels: KIND: BUG

#4971 Print user-friendly error messages when a command is not found, before calling the sandbox
  master_changes.md
  src/state/shellscripts/bwrap.sh
  src/state/shellscripts/sandbox_exec.sh
Labels: AREA: UI

#4940 Windows: remove double printing on commands and their output
  master_changes.md
  src/core/opamProcess.ml
Labels: KIND: BUG, AREA: PORTABILITY

#4934 Actually permit multiple state caches to co-exist
  master_changes.md
  src/state/opamRepositoryState.ml
Labels: KIND: BUG
