Repository ocaml/opam, pull requests merged in 2022-10, with the labels that each got.

#5295 Fix behaviour of menu and depexts in non-interactive environments
  master_changes.md
  src/client/opamSolution.ml
  src/core/opamConsole.ml
  src/core/opamConsole.mli
  src/state/opamEnv.ml
  tests/reftests/depexts.test
  tests/reftests/pin.test
Labels: STATE: READY TO MERGE

#5236 Fix lots of issues with autopin, deps-only, dev deps, depexts...
  master_changes.md
  src/client/opamAuxCommands.ml
  src/client/opamClient.ml
  src/client/opamSolution.ml
  src/client/opamSwitchCommand.ml
  src/state/opamSwitchState.ml
  tests/reftests/autopin.test
  tests/reftests/dune.inc
  tests/reftests/run.ml
Labels: STATE: READY TO MERGE

#5304 reftests: some opam root version upgrade & fixes
  master_changes.md
  tests/reftests/opamroot-versions.test
Labels: AREA:TEST, STATE: READY TO MERGE

#5311 doc: update switch manpage
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#5315 opamClient: pass dl_cache from initConfig to config
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/init.test
Labels: STATE: READY TO MERGE

#5263 Fix all empty conflict messages
  master_changes.md
  src/solver/opamCudf.ml
  tests/reftests/conflict-badversion.test
  tests/reftests/conflict-core.test
  tests/reftests/empty-conflicts-001.test
  tests/reftests/empty-conflicts-002.test
  tests/reftests/empty-conflicts-003.test
  tests/reftests/empty-conflicts-004.test
  tests/reftests/empty-conflicts-005.test
  tests/reftests/empty-conflicts-006.test
  tests/reftests/install-formula.test
  tests/reftests/install-pgocaml.test
  tests/reftests/unhelpful-conflicts-001.test
Labels: KIND: BUG, AREA: ENGINE, IMPORTANT, STATE: READY TO MERGE

#5284 Reset the "jobs" config variable when upgrading from opam 2.0
  master_changes.md
  src/state/opamFormatUpgrade.ml
  tests/reftests/opamroot-versions.test
  tests/reftests/upgrade-two-point-o.test
Labels: PR: WAITING FOR REVIEW

#5325 Allow opam pin remove to take a package as argument
  master_changes.md
  src/client/opamCommands.ml
  src/state/opamPinned.ml
  src/state/opamPinned.mli
  tests/reftests/pin.test
Labels: KIND: FEATURE WISH, AREA: UI
