Repository ocaml/opam, pull requests merged in 2022-09, with the labels that each got.

#5261 Fix --best-effort regression introduced in #4975
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/best-effort.test
  tests/reftests/dune.inc
Labels: KIND: BUG, AREA: ENGINE, STATE: READY TO MERGE

#5212 Create opam root in `%LOCALAPPDATA%\opam` on Windows
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  src/core/opamStd.ml
  src/state/opamEnv.ml
  src/state/opamStateConfig.ml
  src/state/opamStateConfig.mli
Labels: STATE: READY TO MERGE

#5270 Add some tests showing the unhelpful conflict messages mentionned in #4373
  master_changes.md
  tests/reftests/dune.inc
  tests/reftests/unhelpful-conflicts-001.test
Labels: AREA:TEST, IMPORTANT

#5219 Update subpath display
  master_changes.md
  src/client/opamAction.ml
  src/client/opamAuxCommands.ml
  src/client/opamPinCommand.ml
  src/core/opamFilename.ml
  src/core/opamFilename.mli
  src/core/opamUrl.ml
  src/core/opamUrl.mli
  src/repository/opamRepository.ml
  src/state/opamUpdate.ml
  tests/reftests/rec-pin.test
Labels: AREA: UI, STATE: READY TO MERGE

#5258 Do not rebuild packages when an extra-source's url changes but not its checksum
  master_changes.md
  src/format/opamFile.ml
  tests/reftests/dune.inc
  tests/reftests/rebuild.test
Labels: AREA: ENGINE, STATE: READY TO MERGE

#5280 Var: catch an package not found error and print skipping message
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamConfigCommand.ml
  tests/reftests/var-option.test
Labels: STATE: READY TO MERGE

#5277 Explain vendored mode more clearly in configure
  configure
  configure.ac
  master_changes.md
  src_ext/Makefile
Labels: AREA: UI, STATE: READY TO MERGE

#5281 CI: Fix Cygwin Cache
  .github/scripts/cygwin.cmd
  master_changes.md
Labels: STATE: READY TO MERGE

#5161 Require autoconf 2.71 for configure
  .github/workflows/ci.ml
  .github/workflows/lib.ml
  .github/workflows/main.yml
  configure
  master_changes.md
  shell/autogen
Labels: STATE: READY TO MERGE

#5285 Reftest: add path replacement command command
  master_changes.md
  tests/reftests/assume-built.test
  tests/reftests/inplace.test
  tests/reftests/parallel.test
  tests/reftests/repository.test
  tests/reftests/run.ml
  tests/reftests/working-dir.test
Labels: AREA:TEST

#5268 Introduce dummy-success & dummy-failure os-family to make testing depexts behaviour easier
  master_changes.md
  src/client/opamSolution.ml
  src/state/opamSysInteract.ml
  src/state/opamSysInteract.mli
  tests/reftests/dune.inc
  tests/reftests/pin.test
  tests/reftests/pin.unix.test
Labels: AREA:TEST, AREA: DEPEXTS, STATE: READY TO MERGE

#5290 Remove src/client/no-git-version when calling make clean
  Makefile
  master_changes.md
Labels: STATE: READY TO MERGE

#5146 Repository update with no changes: cache part
  master_changes.md
  src/state/opamUpdate.ml
  src/state/opamUpdate.mli
  tests/reftests/repository.test
Labels: STATE: READY TO MERGE

#5293 Fix mangling of `PATH` during cygvoke
  master_changes.md
  src/core/opamProcess.ml
Labels: KIND: BUG, AREA: PORTABILITY, STATE: READY TO MERGE

#5257 Do not infinitly check for depexts when the system package manager fails
  master_changes.md
  src/client/opamSolution.ml
  tests/reftests/depexts.test
  tests/reftests/dune.inc
  tests/reftests/run.ml
Labels: KIND: BUG, AREA: DEPEXTS, STATE: READY TO MERGE

#5297 Make the plugin lookup faster when mistyping a subcommand
  master_changes.md
  src/client/opamCliMain.ml
Labels: STATE: READY TO MERGE

#5289 Finer definition of the --ignore-constraints-on documentation
  master_changes.md
  src/client/opamArg.ml
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#5250 Upgrade the bootstrap compiler to OCaml 4.14.0
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  release/Makefile
  src_ext/Makefile
Labels: STATE: READY TO MERGE

#5214 Rename `--with-tools` to `--with-dev-setup`
  doc/pages/Manual.md
  master_changes.md
  src/client/opamAction.ml
  src/client/opamAction.mli
  src/client/opamArg.ml
  src/client/opamClient.ml
  src/client/opamClientConfig.mli
  src/client/opamCommands.ml
  src/client/opamListCommand.ml
  src/client/opamListCommand.mli
  src/client/opamLockCommand.ml
  src/client/opamSolution.ml
  src/client/opamTreeCommand.ml
  src/format/opamFilter.ml
  src/format/opamFilter.mli
  src/state/opamFileTools.ml
  src/state/opamPackageVar.ml
  src/state/opamPackageVar.mli
  src/state/opamPinned.ml
  src/state/opamStateConfig.ml
  src/state/opamStateConfig.mli
  src/state/opamSwitchState.ml
  src/state/opamSwitchState.mli
  tests/reftests/dune.inc
  tests/reftests/with-dev-setup.test
Labels: STATE: READY TO MERGE

#5299 Args: externalise some package selections flags
  master_changes.md
  src/client/opamArg.ml
  src/client/opamArg.mli
  src/client/opamCommands.ml
Labels: STATE: READY TO MERGE

#5301 reftests: generalise opam root version test
  master_changes.md
  tests/reftests/opamroot-versions.test
Labels: AREA:TEST

#5300 More clear message for pinned package update that have local changes
  master_changes.md
  src/state/opamUpdate.ml
  tests/reftests/assume-built.test
  tests/reftests/inplace.test
  tests/reftests/lock.test
  tests/reftests/update-upgrade.test
  tests/reftests/working-dir.test
Labels: AREA: UI, STATE: READY TO MERGE
