Repository ocaml/opam, pull requests merged in 2022-07, with the labels that each got.

#5179 Add some tests showing how --working-dir behaves on updated dependency constraints
  master_changes.md
  tests/reftests/working-dir.test
Labels: AREA:TEST

#4844 Cygpath the PATH from opam env
  master_changes.md
  src/client/opamConfigCommand.ml
  src/core/opamSystem.ml
  src/core/opamSystem.mli
Labels: AREA: PORTABILITY

#5176 _Correct_ trying to be too clever when upgrading switches from opam 2.0
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  src/core/opamCompat.ml
  src/core/opamCompat.mli
  src/state/opamSwitchState.ml
  tests/reftests/dune.inc
  tests/reftests/upgrade-two-point-o.test
Labels: KIND: BUG

#4816 Environments for PowerShell and Windows command line
  master_changes.md
  src/client/opamArg.ml
  src/client/opamCommands.ml
  src/client/opamConfigCommand.ml
  src/client/opamConfigCommand.mli
  src/core/opamCompat.ml
  src/core/opamCompat.mli
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/core/opamStubs.dummy.ml
  src/core/opamStubs.mli
  src/format/opamTypes.mli
  src/format/opamTypesBase.ml
  src/state/opamEnv.ml
  src/stubs/win32/opamWin32Stubs.ml
  src/stubs/win32/opamWindows.c
Labels: AREA: PORTABILITY

#5155 Console menu: don't print special characters when output is not tty
  master_changes.md
  src/core/opamConsole.ml
Labels: AREA: UI

#5181 switch import: fix installed packages reinstall when import file changed
  master_changes.md
  src/client/opamSwitchCommand.ml
  tests/reftests/dune.inc
  tests/reftests/switch-import.test
Labels: KIND: BUG
