Repository ocaml/opam, pull requests merged in 2022-11, with the labels that each got.

#4968 repository: on set-url fetch failure (sync or file error), revert url change an fetch old one
  master_changes.md
  src/client/opamCommands.ml
  src/core/opamFilename.ml
  src/core/opamFilename.mli
  tests/reftests/repository.test
Labels: AREA: REPOSITORY, STATE: READY TO MERGE

#5329 Reftest: `opam list` add an usecase with faulty dependencies computation
  master_changes.md
  tests/reftests/list.test
Labels: KIND: BUG, AREA:TEST

#5338 Fix cudf weak dependencies computation
  master_changes.md
  src/solver/opamCudf.ml
  tests/reftests/init.test
  tests/reftests/list.test
Labels: KIND: BUG, AREA: SOLVER

#5340 Update IRC links
  README.md
  doc/pages/FAQ.md
  master_changes.md
Labels: STATE: READY TO MERGE

#5228 Use the default criteria during reinstall/upgrade when requesting at least one non-installed package
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/reinstall.test
Labels: KIND: BUG, AREA: SOLVER, STATE: READY TO MERGE

#5229 Show the reason for installing packages when using opam reinstall
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/reinstall.test
Labels: KIND: BUG, AREA: SOLVER, STATE: READY TO MERGE

#5343 Extend the documentation of the --cudf argument
  master_changes.md
  src/client/opamArg.ml
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#5337 Move dependencies computation from `opam-solver` to `opam-state`
  master_changes.md
  src/client/opamClient.ml
  src/client/opamCommands.ml
  src/client/opamListCommand.ml
  src/client/opamLockCommand.ml
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/solver/opamCudf.ml
  src/solver/opamCudf.mli
  src/solver/opamSolver.ml
  src/solver/opamSolver.mli
  src/state/opamSwitchState.ml
  src/state/opamSwitchState.mli
Labels: STATE: READY TO MERGE

#5320 Reftests: Make the binary name of opam the same accross platforms
  master_changes.md
  src/client/dune
  tests/reftests/dune.inc
  tests/reftests/gen.ml
  tests/reftests/run.ml
Labels: AREA:TEST, STATE: READY TO MERGE

#5308 Add opam pin remove --all
  master_changes.md
  src/client/opamCommands.ml
  src/core/opamStd.ml
  src/core/opamStd.mli
  tests/reftests/pin.test
Labels: KIND: FEATURE WISH, AREA: UI, STATE: READY TO MERGE

#5364 Fix trailing space on header messages
  master_changes.md
  src/core/opamConsole.ml
  tests/reftests/init.test
Labels: AREA: UI, STATE: READY TO MERGE
