Repository ocaml/opam, pull requests merged in 2022-03, with the labels that each got.

#4993 Fix handling of `opam-lock` with multiple interdependent packages
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamLockCommand.ml
  tests/reftests/lock.test
  tests/reftests/run.ml
Labels: PR: QUEUED

#5045 Order the actions listing by action/package
  master_changes.md
  src/client/opamSolution.ml
  src/solver/opamActionGraph.ml
  src/solver/opamActionGraph.mli
  src/solver/opamSolver.ml
  tests/reftests/avoid-version.test
  tests/reftests/clean.test
  tests/reftests/cli-versioning.test
  tests/reftests/conflict-resto.test
  tests/reftests/cudf-preprocess.test
  tests/reftests/dot-install.test
  tests/reftests/init.test
  tests/reftests/legacy-git.test
  tests/reftests/legacy-local.test
  tests/reftests/list.test
  tests/reftests/lock.test
  tests/reftests/opamroot-versions.test
  tests/reftests/opamrt-big-upgrade.test
  tests/reftests/opamrt-dep-cycle.test
  tests/reftests/opamrt-reinstall.test
  tests/reftests/orphans.test
  tests/reftests/pat-sub.test
  tests/reftests/pin.test
  tests/reftests/remove.test
  tests/reftests/repository.test
  tests/reftests/shared-fetch.test
  tests/reftests/switch-creation.test
  tests/reftests/switch-invariant.test
  tests/reftests/upgrade-format.test
  tests/reftests/var-option.test
Labels: AREA: UI

#5097 Github deprecation of `git://` protocol updates
  doc/pages/Manual.md
  master_changes.md
  tests/reftests/legacy-git.test
  tests/reftests/upgrade-format.test
Labels: AREA: DOCUMENTATION

#5104 Silence w70
  master_changes.md
  src/core/dune
  src/solver/dune
  src/tools/dune
  src/tools/opam_installer.ml
Labels: AREA: BUILD

#4941 Preserved format errors handling
  master_changes.md
  src/format/opamFile.ml
Labels: KIND: BUG

#5095 Bump vendored deps and add maintenance guide to `src_ext`
  README.md
  master_changes.md
  src_ext/HACKING.md
  src_ext/Makefile.dune
  src_ext/Makefile.sources
  src_ext/patches/cmdliner.common/0001-Escape-default-values.patch
Labels: AREA: BUILD
