Repository ocaml/opam, pull requests merged in 2022-08, with the labels that each got.

#5057 Use the new menus for the initial setup too
  master_changes.md
  src/state/opamEnv.ml
Labels: AREA: UI

#5215 Update `OpamAction.install_package` documentation
  master_changes.md
  src/client/opamAction.mli
Labels: AREA: DOCUMENTATION

#5047 Fix auto pinning and depext handling
  master_changes.md
  src/client/opamClient.ml
  src/state/opamSwitchState.ml
  tests/reftests/dune.inc
  tests/reftests/pin.unix.test
Labels: KIND: BUG

#5235 `opam admin list --environement` values
  master_changes.md
  src/client/opamAdminCommand.ml
Labels: KIND: BUG, AREA: DOCUMENTATION

#5262 Fix the reftests under some heavy parallel hardwear
  master_changes.md
  tests/reftests/working-dir.test
Labels: AREA:TEST

#5267 Fix sandbox ccache symlink resolution
  master_changes.md
  src/state/shellscripts/bwrap.sh
Labels: KIND: BUG, AREA: SANDBOX
