Repository ocaml/opam, pull requests merged in 2022-04, with the labels that each got.

#5098 Add `jsonm` and `uutf` dependencies
  .gitignore
  configure
  configure.ac
  master_changes.md
  src_ext/Makefile
  src_ext/Makefile.packages
  src_ext/Makefile.sources
  src_ext/dune-jsonm-src
  src_ext/dune-uutf-src
  src_ext/patches/jsonm.pkg/0001-remove-uchar-dep.patch
Labels: AREA: BUILD

#5109 Fix repository loading
  master_changes.md
  src/state/opamUpdate.ml
  tests/reftests/repository.test
Labels: KIND: BUG

#5053 Reimplement the depext UI with a menu
  master_changes.md
  src/client/opamPinCommand.ml
  src/client/opamSolution.ml
  src/core/opamConsole.ml
  src/core/opamConsole.mli
  src/core/opamCoreConfig.ml
  src/core/opamCoreConfig.mli
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/format/opamTypesBase.ml
  tests/reftests/assume-built.test
  tests/reftests/clean.test
  tests/reftests/conflict-resto.test
  tests/reftests/inplace.test
  tests/reftests/legacy-git.test
  tests/reftests/legacy-local.test
  tests/reftests/list.test
  tests/reftests/lock.test
  tests/reftests/opamroot-versions.test
  tests/reftests/orphans.test
  tests/reftests/source.test
  tests/reftests/switch-set.test
  tests/reftests/upgrade-format.test
  tests/reftests/working-dir.test
Labels: AREA: UI

#5082 Fix working-dir & fetching non pinned packages
  master_changes.md
  src/client/opamSolution.ml
  tests/reftests/working-dir.test
Labels: KIND: BUG

#5117 Bump opam-file-format to 2.1.4
  .github/workflows/ci.ml
  .github/workflows/main.yml
  appveyor.yml
  configure
  configure.ac
  master_changes.md
  opam-admin.opam
  opam-format.opam
  src_ext/Makefile.sources
Labels: AREA: BUILD

#5118 Rebuild packages only when what is going to be installed can change
  master_changes.md
  src/format/opamFile.ml
  src/format/opamFile.mli
  src/state/opamSwitchState.ml
  tests/reftests/dune.inc
  tests/reftests/reinstall.test
Labels: AREA: ENGINE, IMPORTANT

#4981 Add some debug log to OpamCudf.extract_explanations to help debug #4373
  master_changes.md
  src/solver/opamCudf.ml
Labels: AREA: SOLVER

#4817 Fallback to copying on symlink-less MSYS2
  master_changes.md
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/core/opamSystem.ml
  src/core/opamSystem.mli
Labels: AREA: PORTABILITY
