Repository ocaml/opam, pull requests merged in 2022-01, with the labels that each got.

#4987 Make the status of pinned packages more explicit
  master_changes.md
  src/client/opamSolution.ml
  tests/reftests/opamrt-reinstall.test
  tests/reftests/upgrade-format.test
Labels: AREA: UI

#4998 Improve performance of opam show by 300% when the package to show is given explicitly or unique
  master_changes.md
  src/client/opamListCommand.ml
Labels: AREA: ENGINE

#4421 ~Reorder options,~ fix brew instructions, spelling
  doc/pages/Install.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#4435 Update opam repository man doc
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: DOCUMENTATION

#4982 Fix empty conflict explanations
  master_changes.md
  src/solver/opamCudf.ml
  tests/reftests/conflict-resto.test
Labels: AREA: SOLVER, IMPORTANT
