Repository ocaml/opam, pull requests merged in 2023-05, with the labels that each got.

#5417 Fully revertible environment updates
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamConfigCommand.ml
  src/format/opamFile.ml
  src/format/opamPath.ml
  src/format/opamPath.mli
  src/state/opamEnv.ml
  src/state/opamEnv.mli
  src/state/opamFileTools.ml
  tests/reftests/clean.test
  tests/reftests/env.test
  tests/reftests/lint.test
Labels: PR: WAITING FOR REVIEW

#4823 Use OCaml code to copy/move/remove directories instead of unix commands
  master_changes.md
  src/core/opamFilename.ml
  src/core/opamSystem.ml
Labels: AREA: PORTABILITY

#5512 doc: `?` evaluates to `true` if defined
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#5527 Do not silently disable mccs if a C++ compiler is not present
  configure
  configure.ac
  master_changes.md
Labels: AREA: BUILD, STATE: READY TO MERGE

#5456 init: change shell setup defaut to true
  master_changes.md
  src/state/opamEnv.ml
Labels: AREA: UI, STATE: READY TO MERGE

#5532 Ensure all make targets are run serially
  Makefile
  master_changes.md
Labels: AREA: BUILD, STATE: READY TO MERGE

#5540 Fix opam init menu default
  master_changes.md
  src/state/opamEnv.ml
Labels: STATE: READY TO MERGE

#5538 Fix opam installing packages without checking their checksum when the local cache is corrupted in some cases
  master_changes.md
  src/repository/opamRepository.ml
  tests/reftests/dune.inc
  tests/reftests/local-cache.test
Labels: AREA: ENGINE, STATE: READY TO MERGE

#5444 2.1.5 backport commits
  .github/scripts/hygiene.sh
  CHANGES
  configure
  configure.ac
  doc/pages/Manual.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
  opam.opam
  src/client/opamAction.ml
  src/client/opamClient.ml
  src/repository/opamGit.ml
  src/repository/opamHg.ml
  src/repository/opamRepository.ml
  src/state/opamEnv.ml
  src/state/opamEnv.mli
  tests/reftests/dune.inc
  tests/reftests/env.test
  tests/reftests/init.test
  tests/reftests/local-cache.test
  tests/reftests/opamrt-big-upgrade.test
  tests/reftests/run.ml
Labels: STATE: READY TO MERGE
