Repository ocaml/opam, pull requests merged in 2023-07, with the labels that each got.

#5385 Add `admin` reftest
  master_changes.md
  tests/reftests/admin-add-constraint.test
  tests/reftests/admin.test
  tests/reftests/dune.inc
Labels: AREA:TEST, PR: WAITING FOR REVIEW

#5595 `opam admin lint`: clean output when stdout is not tty
  master_changes.md
  src/core/opamConsole.ml
  tests/reftests/admin.test
Labels: AREA: UI

#5555 Apply `autoupdate` to silence `autogen` warnings
  .github/scripts/main/hygiene.sh
  configure.ac
  master_changes.md
  release/Makefile
  shell/get_version.ml
Labels: STATE: READY TO MERGE

#5579 Update bootstrap to use FlexDLL 0.43 from ocaml/flexdll
  .github/scripts/main/ocaml-cache.sh
  master_changes.md
  src_ext/Makefile
Labels: STATE: READY TO MERGE

#5598 gha: fix master cli version check
  .github/scripts/main/hygiene.sh
  master_changes.md
Labels: STATE: READY TO MERGE

#5603 Bump to 2.2.0~alpha2~dev
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
  opam.opam
Labels: STATE: READY TO MERGE

#5545 init: install cygwin internally
  master_changes.md
  src/client/opamClient.ml
  src/client/opamClient.mli
  src/client/opamCommands.ml
  src/client/opamInitDefaults.ml
  src/client/opamInitDefaults.mli
  src/client/opamSolution.ml
  src/state/opamSysInteract.ml
  src/state/opamSysInteract.mli
Labels: STATE: READY TO MERGE

#5522 configure: Ensure a complementary (32bit on 64bit platforms and 64bit on 32bit platforms) C compiler is installed on Windows
  configure
  configure.ac
  master_changes.md
Labels: AREA: PORTABILITY

#5481 Rebuild the reftest roots if root version changes
  master_changes.md
  tests/reftests/dune
  tests/reftests/dune.inc
  tests/reftests/gen.ml
Labels: STATE: READY TO MERGE

#5420 release script: Add ppc64le and s390x support
  master_changes.md
  release/Makefile
  release/release.sh
  shell/install.sh
Labels: STATE: READY TO MERGE

#5612 Various cleanups related to OCaml 5.0
  Makefile.config.in
  configure
  configure.ac
  master_changes.md
  opam-core.opam
  src/client/opamCLIVersion.ml
  src/core/dune
Labels: AREA: BUILD, STATE: READY TO MERGE
