Repository ocaml/opam, pull requests merged in 2023-04, with the labels that each got.

#5499 depexts: reword message
  master_changes.md
  src/client/opamSolution.ml
  tests/reftests/autopin.test
  tests/reftests/depexts.test
  tests/reftests/pin.test
Labels: STATE: READY TO MERGE

#5514 Update to latest msvs-detect
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  shell/msvs-detect
Labels: STATE: READY TO MERGE

#5525 Setup benchmarking using current-bench
  Makefile
  bench.Dockerfile
  master_changes.md
  tests/bench/bench.ml
  tests/bench/dune
Labels: AREA:TEST, AREA: PERFORMANCE

#5507 Fix linting on opam-crowbar.opam
  master_changes.md
  src/crowbar/opam-crowbar.opam
Labels: STATE: READY TO MERGE

#5511 Stop the configure script from downloading and vendoring dependencies by default
  .github/scripts/main/main.sh
  configure
  configure.ac
  master_changes.md
  release/Dockerfile.in
Labels: AREA: BUILD, STATE: READY TO MERGE
