Repository ocaml/opam, pull requests merged in 2023-09, with the labels that each got.

#5654 Resolve real path on `OpamSystem` temporary directory creation
  master_changes.md
  src/core/opamSystem.ml
  tests/reftests/run.ml
Labels: PR: WAITING FOR REVIEW

#5649 admin: add `update-extrafiles` command
  doc/man/opam-admin-topics.inc
  master_changes.md
  src/client/opamAdminCommand.ml
  tests/reftests/admin.test
Labels: AREA: REPOSITORY

#5662 Fix the sandbox scripts in absence of the OPAMROOT variable
  master_changes.md
  src/state/shellscripts/bwrap.sh
  src/state/shellscripts/sandbox_exec.sh
Labels: KIND: BUG, IMPORTANT

#5652 opam lint: Allow to mark a set of warnings as errors
  master_changes.md
  src/client/opamArg.ml
  src/client/opamArg.mli
  src/client/opamCommands.ml
  tests/reftests/lint.test
Labels: KIND: FEATURE WISH, AREA: UI, STATE: READY TO MERGE

#5607 Fix `OPAMFETCH`/`OPAMCURL` handling
  .github/scripts/cygwin.cmd
  master_changes.md
  src/repository/opamRepositoryConfig.ml
  tests/reftests/download.test
  tests/reftests/dune.inc
  tests/reftests/run.ml
Labels: STATE: READY TO MERGE

#5668 Update Windows section of README
  README.md
Labels: AREA: DOCUMENTATION

#5686 OPAMVERBOSE: Fix `level` by flipping the `env_level` implementation
  master_changes.md
  src/core/opamStd.ml
  tests/reftests/core-config.test
  tests/reftests/dune.inc
Labels: STATE: READY TO MERGE
