Repository ocaml/opam, pull requests merged in 2023-08, with the labels that each got.

#5629 `OpamFilter` file substitutions with source & destination
  master_changes.md
  src/format/opamFilter.ml
  src/format/opamFilter.mli
Labels: STATE: READY TO MERGE

#5633 Expose string_interp_regex
  master_changes.md
  src/format/opamFilter.mli
Labels: STATE: READY TO MERGE

#5635 Fix "make cold" on Windows when gcc is available
  Makefile
  master_changes.md
Labels: STATE: READY TO MERGE

#5640 log: more precise missing extra-files populating message
  master_changes.md
  src/state/opamFileTools.ml
  tests/reftests/admin.test
Labels: STATE: READY TO MERGE

#5639 Fix extra-files handling on linting
  master_changes.md
  src/client/opamCommands.ml
  tests/reftests/lint.test
Labels: KIND: BUG, STATE: READY TO MERGE

#5613 opam tree: Allow packages with a specific version, directories or local opam files, as input
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamTreeCommand.ml
  src/client/opamTreeCommand.mli
  tests/reftests/tree.test
Labels: AREA: UI, STATE: READY TO MERGE

#5560 Reftests: add tests to check url handling behaviours
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  tests/reftests/archive.test
  tests/reftests/dune.inc
  tests/reftests/extrafile.test
  tests/reftests/extrasource.test
  tests/reftests/local-cache.test
Labels: STATE: READY TO MERGE
