Repository ocaml/opam, pull requests merged in 2023-03, with the labels that each got.

#4926 Upgrade root version to 2.2~alpha
  master_changes.md
  src/format/opamFile.ml
  src/state/opamFormatUpgrade.ml
  tests/reftests/init.test
  tests/reftests/opamroot-versions.test
Labels: STATE: READY TO MERGE

#5451 Enforce the macOS sandbox script to use /bin/bash instead of /usr/bin/env bash for a more consistent experience
  master_changes.md
  src/state/shellscripts/sandbox_exec.sh
Labels: KIND: BUG, AREA: SANDBOX

#5436 Variable for package manager
  master_changes.md
  src/client/opamClient.ml
  src/client/opamCommands.ml
  src/client/opamConfigCommand.ml
  src/client/opamSolution.ml
  src/format/opamFile.ml
  src/format/opamFile.mli
  src/state/opamSwitchState.ml
  src/state/opamSysInteract.ml
  src/state/opamSysInteract.mli
  tests/reftests/var-option.test
Labels: STATE: READY TO MERGE

#4859 Add Software ID in opam file
  doc/pages/Manual.md
  doc/pages/Usage.md
  master_changes.md
  opam-core.opam
  src/client/opamConfigCommand.ml
  src/client/opamListCommand.ml
  src/core/dune
  src/core/opamHash.ml
  src/core/opamSHA.ml
  src/core/opamSHA.mli
  src/core/opamSWHID.ml
  src/core/opamSWHID.mli
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/core/opamSystem.ml
  src/core/opamSystem.mli
  src/format/opamFile.ml
  src/format/opamFile.mli
  src/repository/opamDownload.ml
  src/repository/opamDownload.mli
  src/repository/opamGit.ml
  src/state/opamUpdate.ml
  src/state/opamUpdate.mli
  src_ext/Makefile
  src_ext/Makefile.packages
  src_ext/Makefile.sources
  tests/reftests/dune.inc
  tests/reftests/init.test
  tests/reftests/opamroot-versions.test
  tests/reftests/show.test
  tests/reftests/swhid.unix.test
  tests/reftests/var-option.test
Labels: PR: WAITING FOR REVIEW

#5467 Bump vendored dependency: jsonm 1.0.2
  master_changes.md
  shell/re-patch.sh
  src_ext/Makefile.sources
  src_ext/patches/jsonm.pkg/0001-remove-uchar-dep.patch
Labels: AREA: BUILD

#5465 Remove unused vendored dependency: result
  master_changes.md
  src_ext/Makefile
  src_ext/Makefile.packages
  src_ext/Makefile.sources
Labels: AREA: BUILD

#5326 git: differentiate empty repo and branch not found
  master_changes.md
  src/client/opamPinCommand.ml
  src/repository/opamGit.ml
  tests/reftests/pin.test
Labels: KIND: BUG, AREA: UI

#5452 Implement accessors for `OpamProcess.command` type
  master_changes.md
  src/core/opamProcess.mli
Labels: AREA: API

#5468 Lock: remove url section from generated lock file
  master_changes.md
  src/client/opamLockCommand.ml
  tests/reftests/lock.test
Labels: STATE: READY TO MERGE

#5386 Admin: add packages selection for `add-constraint`
  master_changes.md
  src/client/opamAdminCommand.ml
  tests/reftests/admin-add-constraint.test
Labels: PR: WAITING FOR REVIEW

#5453 depexts: add more precise depext testing family
  .github/workflows/depexts.yml
  master_changes.md
  src/state/opamSysInteract.ml
Labels: AREA:TEST, STATE: READY TO MERGE
