Repository ocaml/opam, pull requests merged in 2023-12, with the labels that each got.

#5737 release: Workaround missing -O option to tar on OpenBSD
  master_changes.md
  release/Makefile
Labels: AREA: PORTABILITY

#5712 switch: more precise message for fatal error on switch creation
  master_changes.md
  src/client/opamSwitchCommand.ml
Labels: AREA: UI, PR: WAITING FOR REVIEW

#5769 Upgrade to mccs.1.1+17
  .github/workflows/ci.ml
  .github/workflows/main.yml
  configure
  configure.ac
  master_changes.md
  opam-solver.opam
  src_ext/Makefile.sources
Labels: PR: WAITING FOR REVIEW
