Repository ocaml/opam, pull requests merged in 2023-01, with the labels that each got.

#5403 Remove unused variable `siz`
  master_changes.md
  src/stubs/libacl/opamACL.c
Labels: AREA: BUILD, STATE: READY TO MERGE

#5342 git, hg: Use full revision
  master_changes.md
  src/repository/opamGit.ml
  src/repository/opamHg.ml
Labels: STATE: READY TO MERGE

#5303 Support --json option in opam tree
  master_changes.md
  src/client/opamTreeCommand.ml
  src/core/opamConsole.ml
  src/core/opamConsole.mli
  tests/reftests/json.unix.test
Labels: PR: QUEUED, STATE: READY TO MERGE

#5348 depexts for MSYS2
  .gitignore
  master_changes.md
  src/state/opamSysInteract.ml
Labels: AREA: PORTABILITY, PR: QUEUED, AREA: DEPEXTS, STATE: READY TO MERGE

#5412 Upgrade spdx_licenses to 1.2.0
  .github/scripts/main/hygiene.sh
  .github/workflows/main.yml
  master_changes.md
  src_ext/Makefile.sources
Labels: STATE: READY TO MERGE

#5407 Log the time dose3's check_request takes
  master_changes.md
  src/solver/opamCudf.ml
Labels: STATE: READY TO MERGE

#5352 Expand variable interpolations in `build-env`
  master_changes.md
  src/client/opamAction.ml
  src/state/opamEnv.ml
  src/state/opamEnv.mli
  tests/reftests/env.test
Labels: STATE: READY TO MERGE

#5350 Fix crash for updates to environment with empty strings
  doc/pages/Manual.md
  master_changes.md
  src/state/opamEnv.ml
  tests/reftests/env.test
Labels: STATE: READY TO MERGE

#5424 Upgrade the vendored sha to 1.15.4
  master_changes.md
  src_ext/Makefile.sources
Labels: STATE: READY TO MERGE
