Repository ocaml/opam, pull requests merged in 2024-12, with the labels that each got.

#6320 Manual: add information when flags (avoid-version, deprecated) were introduced
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#6217 Use a C stub to call the uname function from the C standard library instead of calling the uname POSIX command
  master_changes.md
  src/core/opamCommonStubs.c
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/core/opamStubs.mli
  src/core/opamStubs.unix.ml
  src/core/opamStubsTypes.ml
  src/core/opamUnix.c
  src/core/opamWin32Stubs.win32.ml
  src/state/opamSysPoll.ml
Labels: AREA: PORTABILITY

#6313 Run shellcheck on shell/install.sh and make it pass, add a CI job to check next changes
  .github/scripts/main/hygiene.sh
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  shell/install.sh
Labels: STATE: READY TO MERGE

#6318 Fix opam switch list-available when given several arguments
  master_changes.md
  src/client/opamCommands.ml
  tests/reftests/switch-list-available.test
Labels: KIND: BUG

#6186 Fix `opam switch list-available pkg.version` pattern
  master_changes.md
  src/client/opamCommands.ml
  tests/reftests/switch-list-available.test
Labels: AREA: UI, STATE: READY TO MERGE

#6036 Software Heritage fallback fixes
  .gitignore
  master_changes.md
  src/core/opamFilename.ml
  src/core/opamFilename.mli
  src/core/opamSystem.ml
  src/core/opamSystem.mli
  src/repository/opamDownload.ml
  tests/reftests/download.test
  tests/reftests/swhid.unix.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6326 sandbox: respect the `DUNE_CACHE_ROOT` environment variable if it exists
  master_changes.md
  src/state/shellscripts/bwrap.sh
  src/state/shellscripts/sandbox_exec.sh
Labels: AREA: SANDBOX

#6336 Fix GHA when opam-rt uses a diverging API
  .github/scripts/main/main.sh
Labels: AREA:TEST

#6337 [2.3 backport] Fix GHA when opam-rt uses a diverging API
  .github/scripts/main/main.sh
Labels: AREA:TEST

#6338 docs: Add winget command for installing opam
  doc/pages/Install.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6332 [2.3 backport] Fix opam admin check in the presence of the with-dev-setup variable
  master_changes.md
  src/client/opamAdminCheck.ml
  tests/reftests/admin.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6333 Fix sandboxing support in NixOS
  master_changes.md
  src/state/shellscripts/bwrap.sh
Labels: AREA: SANDBOX, STATE: READY TO MERGE

#6212 Add benchmarks for opam show and String.split
  bench.Dockerfile
  master_changes.md
  tests/bench/bench.ml
Labels: AREA:TEST, STATE: READY TO MERGE, AREA: PERFORMANCE

#6210 perf: optimize OpamString.split
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  src/core/opamStd.ml
Labels: STATE: READY TO MERGE, AREA: PERFORMANCE

#6255 Lookup at gpatch before patch on macOS now that both homebrew and macports expose gpatch as gpatch
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  src/client/opamInitDefaults.ml
  src/core/opamSystem.ml
  tests/lib/patcher.ml
  tests/reftests/repository.test
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#5014 Check that the repositories given to "opam repository remove" actually exist
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamRepositoryCommand.mli
  tests/reftests/repository.test
Labels: AREA: UI, PR: WAITING FOR REVIEW
