Repository ocaml/opam, pull requests merged in 2024-06, with the labels that each got.

#5963 Improvements to `opam init` "Git" menu on Windows
  configure
  configure.ac
  master_changes.md
  shell/context_flags.ml
  src/client/opamClient.ml
  src/core/opamStubs.dummy.ml
  src/core/opamStubs.mli
  src/core/opamStubsTypes.ml
  src/stubs/win32/opamWin32Stubs.ml
  src/stubs/win32/opamWindows.c
Labels: AREA: UI, STATE: READY TO MERGE

#5976 Upgrade the vendored OCaml compiler to 4.14.2
  .github/workflows/ci.ml
  .github/workflows/depexts.yml
  .github/workflows/main.yml
  master_changes.md
  release/Makefile
  src_ext/Makefile
Labels: STATE: READY TO MERGE

#5985 Fix OpamFilter map/fold functions
  master_changes.md
  src/format/opamFilter.ml
Labels: STATE: READY TO MERGE

#5983 Don't display undefined variable warnings when evaluating the `?` operator
  master_changes.md
  src/state/opamSwitchState.ml
  tests/reftests/resolve-variables.test
Labels: KIND: BUG, STATE: READY TO MERGE

#5993 Harden OpamStd.Sys.check_dll
  master_changes.md
  src/core/opamStd.ml
Labels: STATE: READY TO MERGE

#5995 Always pass `--no-write-registry` to Cygwin setup
  master_changes.md
  src/state/opamSysInteract.ml
Labels: STATE: READY TO MERGE

#5996 Don't allow make to become shadowed
  master_changes.md
  src/state/opamEnv.ml
Labels: STATE: READY TO MERGE

#5998 Wind CI forwards to the Windows compilers
  .github/workflows/ci.ml
  .github/workflows/depexts.yml
  .github/workflows/main.yml
  master_changes.md
Labels: STATE: READY TO MERGE

#5999 Display lock hold/release messages on stderr instead of stdout
  master_changes.md
  src/core/opamConsole.ml
  src/core/opamConsole.mli
  src/core/opamSystem.ml
Labels: STATE: READY TO MERGE

#5992 Extend OpamConsole.menu to support 35 options
  master_changes.md
  src/core/opamConsole.ml
  src/core/opamConsole.mli
Labels: STATE: READY TO MERGE

#5972 Change default rule for `PKG_CONFIG_PATH` and `MANPATH` to `target`
  master_changes.md
  src/state/opamEnv.ml
  tests/reftests/env.win32.test
Labels: KIND: BUG

#5997 Rename and slightly repurpose `OpamClient.git_for_windows_check`
  master_changes.md
  src/client/opamClient.ml
Labels: STATE: READY TO MERGE

#5991 Disentangle `OpamProcess.resolve_command` and `OpamSystem.resolve_command`
  master_changes.md
  src/core/opamProcess.ml
  src/core/opamProcess.mli
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/core/opamSystem.ml
  src/core/opamSystem.mli
Labels: STATE: READY TO MERGE

#6002 Do not special case the rewriting rule for the PKG_CONFIG_PATH environment variable
  doc/pages/Manual.md
  master_changes.md
  src/state/opamEnv.ml
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#5994 API: Allow explicit installation of system packages
  master_changes.md
  src/client/opamSolution.ml
  src/client/opamSolution.mli
Labels: STATE: READY TO MERGE, PR: WAITING FOR REVIEW

#5984 Harden curl output parsing
  master_changes.md
  src/core/opamProcess.ml
  src/repository/opamDownload.ml
Labels: KIND: BUG, STATE: READY TO MERGE

#6003 Args: stop hiding the Windows specific arguments of opam init on non-Windows platforms
  master_changes.md
  src/client/opamArg.mli
  src/client/opamArgTools.ml
  src/client/opamArgTools.mli
  src/client/opamCommands.ml
Labels: STATE: READY TO MERGE

#6005 Fix bug in recursion case in `OpamSystem.mk_temp_dir`
  master_changes.md
  src/core/opamSystem.ml
Labels: KIND: BUG

#5977 Display a note when reloading a repository
  master_changes.md
  src/repository/opamRepository.ml
  src/state/opamRepositoryState.ml
  tests/reftests/download.test
  tests/reftests/dune.inc
  tests/reftests/update.test
Labels: AREA: UI, STATE: READY TO MERGE

#6000 Small refactoring and fixes to `opam init` on Windows.
  master_changes.md
  src/client/opamAction.ml
  src/client/opamClient.ml
  src/client/opamInitDefaults.ml
  src/client/opamSolution.ml
  src/core/opamCompat.ml
  src/core/opamCompat.mli
  src/core/opamProcess.ml
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/core/opamStubs.dummy.ml
  src/core/opamStubs.mli
  src/core/opamSystem.ml
  src/state/opamEnv.ml
  src/state/opamEnv.mli
  src/state/opamGlobalState.ml
  src/state/opamSysInteract.ml
  src/state/opamSysInteract.mli
  src/state/opamSysPoll.ml
  src/stubs/win32/opamWin32Stubs.ml
  src/stubs/win32/opamWindows.c
Labels: PR: WAITING FOR REVIEW

#5457 windows: opam root redirection when path contains spaces
  master_changes.md
  src/client/opamArg.ml
  src/client/opamCliMain.ml
  src/client/opamClient.ml
  src/client/opamClientConfig.ml
  src/client/opamClientConfig.mli
  src/client/opamCommands.ml
  src/core/opamConsole.ml
  src/core/opamConsole.mli
  src/core/opamSystem.ml
  src/core/opamSystem.mli
  src/format/opamPath.ml
  src/format/opamPath.mli
  src/state/opamStateConfig.ml
  src/state/opamStateConfig.mli
  tests/reftests/env.test
  tests/reftests/env.unix.test
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#6008 Update install.sh with opam 2.2.0~beta3
  shell/install.sh
Labels: AREA: RELEASE

#6016 Fix the lower-bound constraint on ocaml-re
  master_changes.md
  opam-client.opam
Labels: STATE: READY TO MERGE

#6024 Fix a wrong use of OpamFilename.of_string
  master_changes.md
  src/format/opamFile.ml
Labels: STATE: READY TO MERGE

#6026 Fix OpamConsole.menu > 9 options
  master_changes.md
  src/core/opamConsole.ml
Labels: KIND: BUG, AREA: UI

#6029 Nullify positions of the extensions fields in OpamFile.OPAM.effective_part
  master_changes.md
  src/format/opamFile.ml
  src/format/opamTypesBase.ml
  src/format/opamTypesBase.mli
  tests/reftests/dune.inc
  tests/reftests/effectively-equal.test
Labels: KIND: BUG, AREA: ENGINE

#6033 Fix `opam init -yn` asking questions on Windows
  master_changes.md
  src/client/opamClient.ml
Labels: KIND: BUG

#5789 Add windows to the release script
  .github/scripts/main/ocaml-cache.sh
  master_changes.md
  release/Makefile
  release/readme.md
  release/release.sh
  src_ext/Makefile
Labels: AREA: PORTABILITY, PR: WAITING FOR REVIEW

#6039 Release 2.2.0~rc1
  CHANGES
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
  opam.opam
Labels: AREA: RELEASE

#6040 Update install.sh with opam 2.2.0~rc1
  shell/install.sh
Labels: AREA: RELEASE

#6058 2.2:Restore signature of OpamStateConfig.opamroot
  master_changes.md
  src/client/opamCliMain.ml
  src/client/opamClientConfig.ml
  src/client/opamCommands.ml
  src/state/opamStateConfig.ml
  src/state/opamStateConfig.mli
Labels: AREA: API

#6057 2.2: Adjust common flags passed to Cygwin setup
  master_changes.md
  src/state/opamSysInteract.ml
Labels: AREA: PORTABILITY
