Repository ocaml/opam, pull requests merged in 2024-02, with the labels that each got.

#5794 Do not check for cppo in the configure script (not used directly anymore)
  configure
  configure.ac
  master_changes.md
Labels: AREA: BUILD

#5797 Fix shell detection on Windows when opam is called via Cygwin's /usr/bin/env even though cmd/powershell is used
  master_changes.md
  src/core/opamStd.ml
  src_ext/Makefile.sources
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#5837 Two (more) environment fixes
  master_changes.md
  src/state/opamEnv.ml
  tests/reftests/env.test
Labels: KIND: BUG

#5796 Disable ACL in Cygwin to avoid permission missmatch errors
  master_changes.md
  src/state/opamSysInteract.ml
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#5849 Documentation: Fix a dead link to SPDX license expressions spec
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#5847 Add `sys-pkg-manager-cmd` in init config
  master_changes.md
  src/client/opamClient.ml
  src/format/opamFile.ml
  src/format/opamFile.mli
Labels: AREA: DEPEXTS, STATE: READY TO MERGE

#5850 fix missing spaces
  master_changes.md
  src/client/opamArg.ml
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#5793 Add winsymlinks:native to the CYGWIN environment variable when running a Cygwin executable on Windows
  doc/pages/Manual.md
  master_changes.md
  src/core/opamProcess.ml
Labels: AREA: PORTABILITY

#5841 Quote all the paths to OPAMROOT when creating the init scripts on Unix
  master_changes.md
  src/core/opamSystem.mli
  src/state/opamEnv.ml
Labels: STATE: READY TO MERGE

#5848 init: on windows, fix handling of 'git-location' when defined in init config
  master_changes.md
  src/client/opamClient.ml
Labels: KIND: BUG, STATE: READY TO MERGE

#5852 gha: update checkout to v4
  .github/workflows/lib.ml
  .github/workflows/main.yml
  master_changes.md
Labels: STATE: READY TO MERGE
