Repository ocaml/opam, pull requests merged in 2024-03, with the labels that each got.

#5843 Opam 2.2 init with MSYS2
  master_changes.md
  src/client/opamArg.ml
  src/client/opamClient.ml
  src/core/opamCoreConfig.ml
  src/core/opamCoreConfig.mli
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/state/opamGlobalState.ml
  src/state/opamSysInteract.ml
  src/state/opamSysInteract.mli
Labels: AREA: PORTABILITY

#5862 Windows: Remove use of deprecated function SHGetFolderPath and use SHGetKnownFolderPath instead
  configure
  configure.ac
  master_changes.md
  shell/context_flags.ml
  src/core/opamStd.ml
  src/core/opamStubs.dummy.ml
  src/core/opamStubs.mli
  src/core/opamStubsTypes.ml
  src/state/opamStateConfig.ml
  src/stubs/win32/opamWin32Stubs.ml
  src/stubs/win32/opamWindows.c
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#5864 Shell integration: Test if file exists before sourcing in fish + powershell
  master_changes.md
  src/state/opamEnv.ml
  tests/reftests/dune.inc
  tests/reftests/init-scripts.unix.test
  tests/reftests/init-scripts.win32.test
Labels: STATE: READY TO MERGE

#5400 Replace the dependency on GNU patch by a strict dependency on git
  doc/pages/Manual.md
  master_changes.md
  src/client/opamInitDefaults.ml
  src/core/opamSystem.ml
  tests/reftests/repository.test
Labels: AREA: PORTABILITY, PR: WAITING FOR REVIEW

#5866 Fish integration: nitpicking
  master_changes.md
  src/state/opamEnv.ml
  src/state/shellscripts/env_hook.fish
  tests/reftests/init-scripts.unix.test
  tests/reftests/init-scripts.win32.test
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#5869 Upgrade the vendored dune to 3.14.0 and other packages to their latest release
  .github/scripts/main/create-ocaml-cache.sh
  .github/workflows/ci.ml
  .github/workflows/main.yml
  .gitignore
  Makefile
  master_changes.md
  src_ext/Makefile
  src_ext/Makefile.dune
  src_ext/Makefile.packages
  src_ext/Makefile.sources
  src_ext/update-sources.sh
Labels: AREA: BUILD, STATE: READY TO MERGE

#5876 Mention the ocaml/infrastructure bugtracker in issue_template.md
  .github/issue_template.md
Labels: STATE: READY TO MERGE

#5880 Allow to compile opam when the environment contains unicode characters on Windows (upgrade to dune 3.14.2)
  master_changes.md
  src_ext/Makefile.dune
Labels: AREA: PORTABILITY, AREA: BUILD, STATE: READY TO MERGE

#5885 Manual: add missing 'since opam 2.2' annotation when mentionning with-dev-setup
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#5891 Revert "Merge pull request #5400 from kit-ty-kate/no-gpatch"
  doc/pages/Manual.md
  master_changes.md
  src/client/opamInitDefaults.ml
  src/core/opamSystem.ml
  tests/reftests/repository.test
Labels: STATE: READY TO MERGE

#5829 Various `eval-variables` fixes and `sys-ocaml-system`
  master_changes.md
  src/client/opamClient.ml
  src/client/opamInitDefaults.ml
  src/core/opamProcess.ml
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/state/opamEnv.ml
  src/state/opamEnv.mli
  src/state/opamFormatUpgrade.ml
  src/state/opamGlobalState.ml
  tests/reftests/dune.inc
  tests/reftests/init-ocaml-eval-variables.unix.test
  tests/reftests/init-ocaml-eval-variables.win32.test
  tests/reftests/init.test
  tests/reftests/opamroot-versions.test
  tests/reftests/var-option.test
Labels: AREA: PORTABILITY
