Repository ocaml/opam, pull requests merged in 2024-11, with the labels that each got.

#6284 Port missing changelog from the 2.3 branch and improve release steps
  CHANGES
  release/readme.md
Labels: AREA: RELEASE

#6292 Release 2.3.0
  .github/scripts/main/preamble.sh
  CHANGES
  configure
  configure.ac
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: AREA: RELEASE

#6293 Add opam 2.3.0 to the install scripts
  master_changes.md
  shell/install.ps1
  shell/install.sh
Labels: AREA: RELEASE

#6289 Use an uppercase character again for the default in interactive questions
  master_changes.md
  src/core/opamConsole.ml
  tests/reftests/assume-built.test
  tests/reftests/autopin.test
  tests/reftests/clean.test
  tests/reftests/config.test
  tests/reftests/conflict-resto.test
  tests/reftests/fetch-package.test
  tests/reftests/init-ocaml-eval-variables.unix.test
  tests/reftests/init-ocaml-eval-variables.win32.test
  tests/reftests/inplace.test
  tests/reftests/json.unix.test
  tests/reftests/legacy-git.test
  tests/reftests/legacy-local.test
  tests/reftests/list-large-dependencies.test
  tests/reftests/lock.test
  tests/reftests/opamroot-versions.test
  tests/reftests/orphans.test
  tests/reftests/pin-legacy.test
  tests/reftests/pin.test
  tests/reftests/rec-pin.test
  tests/reftests/reinstall.test
  tests/reftests/repository.test
  tests/reftests/source.test
  tests/reftests/swhid.unix.test
  tests/reftests/switch-import.test
  tests/reftests/switch-list.test
  tests/reftests/switch-set.test
  tests/reftests/tree.test
  tests/reftests/update-upgrade.test
  tests/reftests/upgrade-format.test
  tests/reftests/upgrade.test
  tests/reftests/var-option.test
  tests/reftests/working-dir.test
Labels: AREA: UI, STATE: READY TO MERGE

#6295 Bring the changelog entry for 2.3.0
  CHANGES
Labels: AREA: RELEASE

#6276 Remove linked switches without failing
  master_changes.md
  src/core/opamSystem.ml
  tests/reftests/dune.inc
  tests/reftests/switch-remove.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6299 Fix the detection of ZDOTDIR when using zsh
  master_changes.md
  src/core/opamStd.ml
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#6303 Avoid issues when using wget2 where the requested url might return an html page instead of the expected content
  master_changes.md
  src/repository/opamDownload.ml
  tests/reftests/download.test
Labels: STATE: READY TO MERGE

#6249 Ensure each repositories stored in repos-config is associated with an URL
  master_changes.md
  src/client/opamClient.ml
  src/format/opamFile.ml
  src/format/opamFile.mli
  src/state/opamFormatUpgrade.ml
  src/state/opamRepositoryState.ml
  tests/reftests/repository.test
Labels: AREA: ENGINE, STATE: READY TO MERGE

#5659 Clarify documentation for `enable` pseudo-variable
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#5396 Run garbage collection once when the main process is waiting for
  master_changes.md
  src/core/opamParallel.ml
Labels: STATE: READY TO MERGE, AREA: PERFORMANCE

#6274 Make it so pin list display the current revision of the pinned repo
  .github/scripts/main/main.sh
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamPinCommand.ml
  tests/reftests/pin.test
  tests/reftests/rec-pin.test
  tests/reftests/switch-import.test
Labels: AREA: UI

#6315 Fix a typo in a documentation string
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE
