Repository ocaml/opam, pull requests merged in 2024-08, with the labels that each got.

#6123 Benchmark opam install --check
  master_changes.md
  tests/bench/bench.ml
Labels: AREA:TEST

#6121 Fix "opam install --check pkg" when pkg depends on a non-existing package
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/dune.inc
  tests/reftests/install-check.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6139 reftest: add reinstall test that shows delayed removal mechanism
  master_changes.md
  tests/reftests/reinstall.test
Labels: AREA:TEST, STATE: READY TO MERGE

#6138 Update the installation documentation after the release of opam 2.2
  doc/pages/Install.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6144 Reduce allocations in opamVersionCompare
  master_changes.md
  src/core/opamVersionCompare.ml
Labels: STATE: READY TO MERGE, AREA: PERFORMANCE

#5518 Speedup OpamVersionCompare by 15%
  master_changes.md
  src/core/opamVersionCompare.ml
Labels: AREA: PERFORMANCE

#6081 GHA: bump version of actions
  .github/workflows/ci.ml
  .github/workflows/depexts.yml
  .github/workflows/main.yml
  master_changes.md
Labels: AREA:TEST

#5363 Documentation: Add some missing environment variable added during a build
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#5375 Add a new --latests-only option to opam list & opam admin list to only work on the set of latest packages
  master_changes.md
  src/client/opamAdminCommand.ml
  src/client/opamArg.ml
  src/client/opamArg.mli
  src/client/opamCommands.ml
  src/client/opamListCommand.ml
  src/client/opamListCommand.mli
  tests/reftests/admin.test
  tests/reftests/dune.inc
  tests/reftests/list-large-dependencies.test
  tests/reftests/list.test
Labels: AREA: UI, STATE: READY TO MERGE

#6149 Add a benchmark for opam list --installed on non-installed packages
  master_changes.md
  tests/bench/bench.ml
Labels: AREA:TEST

#5018 Remove unnecessary copies/move when fetching archives
  master_changes.md
  src/repository/opamRepository.ml
  tests/reftests/download.test
  tests/reftests/swhid.unix.test
Labels: STATE: READY TO MERGE

#6091 Consistent accepted repository links
  master_changes.md
  src/client/opamCommands.ml
  tests/reftests/switch-creation.test
Labels: AREA: UI, STATE: READY TO MERGE

#6151 CLI: add 2.3 in supported versions
  master_changes.md
  src/client/opamArgTools.ml
  src/client/opamCLIVersion.ml
Labels: KIND: BUG, STATE: READY TO MERGE

#6105 Mechanism for reftests filtering
  Makefile
  master_changes.md
  tests/reftests/dune.inc
  tests/reftests/gen.ml
  tests/reftests/run.ml
Labels: STATE: READY TO MERGE

#6087 [2.2] GHA: bump version of actions
  .github/workflows/ci.ml
  .github/workflows/depexts.yml
  .github/workflows/main.yml
  master_changes.md
Labels: AREA:TEST, PR: WAITING FOR REVIEW

#5489 OpamFile: Make all writes atomic
  master_changes.md
  src/core/opamFilename.ml
  src/core/opamFilename.mli
  src/format/opamFile.ml
  src/format/opamFile.mli
  tests/reftests/dot-install.test
  tests/reftests/opamroot-versions.test
  tests/reftests/repository.test
Labels: AREA: ENGINE, STATE: READY TO MERGE

#6147 [2.2 backport] Disable shallow clone by default except for opam repositories
  master_changes.md
  src/repository/opamGit.ml
  src/repository/opamRepository.mli
  src/repository/opamRepositoryBackend.mli
  src/repository/opamVCS.mli
  tests/reftests/dune.inc
  tests/reftests/fetch-package.test
  tests/reftests/source.test
Labels: AREA: ENGINE

#6155 Speedup "make reftest-gen"
  Makefile
  master_changes.md
Labels: AREA:TEST

#6092 release: show the right opam-publish command to run
  release/readme.md
Labels: PR: QUEUED, AREA: RELEASE

#6159 Make the shell environment update hint easier to copy/paste
  master_changes.md
  src/state/opamEnv.ml
  tests/reftests/env.unix.test
Labels: AREA: UI

#6132 Fail when a git submodule fails to update instead of ignoring the error
  .github/scripts/main/preamble.sh
  master_changes.md
  src/repository/opamGit.ml
  tests/reftests/dune.inc
  tests/reftests/git.test
Labels: KIND: BUG

#6130 Add support for opam-0install-cudf 0.5.0
  .github/workflows/ci.ml
  .github/workflows/depexts.yml
  .github/workflows/main.yml
  configure
  configure.ac
  doc/index.html
  master_changes.md
  opam-solver.opam
  src/solver/opamBuiltin0install.ml
  src/solver/opamBuiltinZ3.real.ml
  src/solver/opamCudfCriteria.ml
  src/solver/opamCudfCriteria.mli
  src_ext/Makefile.sources
Labels: AREA: SOLVER, STATE: READY TO MERGE

#5317 Various speedups on tasks that do not require availability information (e.g. opam list --installed)
  master_changes.md
  src/client/opamAdminCheck.ml
  src/client/opamClient.ml
  src/client/opamCommands.ml
  src/client/opamListCommand.ml
  src/client/opamListCommand.mli
  src/client/opamLockCommand.ml
  src/client/opamTreeCommand.ml
  src/format/opamFormula.ml
  src/format/opamFormula.mli
  src/format/opamTypes.mli
  src/solver/opamSolver.ml
  src/solver/opamSolver.mli
  src/state/opamSwitchState.ml
  src/state/opamSwitchState.mli
Labels: AREA: ENGINE, STATE: READY TO MERGE, AREA: PERFORMANCE

#6122 Make "opam install --check" check if all dependencies are installed recursively
  master_changes.md
  src/client/opamClient.ml
  src/client/opamClient.mli
  src/client/opamCommands.ml
  src/format/opamFormula.ml
  src/format/opamFormula.mli
  tests/reftests/install-check.test
Labels: KIND: BUG

#6168 Mitigate problems with curl on Windows 11
  master_changes.md
  src/repository/opamDownload.ml
  tests/reftests/download.test
Labels: KIND: BUG, AREA: PORTABILITY, IMPORTANT, STATE: READY TO MERGE

#6169 [2.2 backport] Mitigate problems with curl on Windows 11
  master_changes.md
  src/repository/opamDownload.ml
  tests/reftests/download.test
Labels: KIND: BUG, AREA: PORTABILITY, STATE: READY TO MERGE

#6172 Release 2.2.1
  CHANGES
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
  opam.opam
Labels: AREA: RELEASE

#6175 release: fix the docker phase
  master_changes.md
  release/Dockerfile.in
Labels: KIND: BUG, AREA: RELEASE

#6176 [2.2 backport] release: fix the docker phase
  master_changes.md
  release/Dockerfile.in
Labels: KIND: BUG, AREA: RELEASE

#6177 [2.1 backport] release: fix the docker phase
  master_changes.md
  release/Dockerfile.in
Labels: KIND: BUG, AREA: RELEASE

#6178 [2.0 backport] release: fix the docker phase
  release/Dockerfile.in
Labels: KIND: BUG, AREA: RELEASE

#6173 Update the install script and changelog after the release of 2.2.1
  CHANGES
  master_changes.md
  release/readme.md
  shell/install.ps1
  shell/install.sh
Labels: AREA: RELEASE

#6182 Fix highly embarrassing mistake in patch transformation
  master_changes.md
  src/core/opamSystem.ml
  tests/lib/patcher.expected
Labels: KIND: BUG

#6183 [2.2 backport] Fix highly embarrassing mistake in patch transformation
  master_changes.md
  src/core/opamSystem.ml
  tests/lib/patcher.expected
Labels: KIND: BUG, STATE: READY TO MERGE
