Repository ocaml/opam, pull requests merged in 2024-01, with the labels that each got.

#5680 Add ./configure --enable-static to compile the opam binary statically
  .github/scripts/cygwin.cmd
  .github/workflows/ci.ml
  .github/workflows/main.yml
  configure
  configure.ac
  master_changes.md
Labels: AREA: PORTABILITY, AREA: BUILD, STATE: READY TO MERGE

#5775 Update Install.md FreeBSD instructions
  doc/pages/Install.md
  master_changes.md
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#5715 opam env: fix carriage return on Cygwin shell
  master_changes.md
  src/client/opamConfigCommand.ml
Labels: KIND: BUG, AREA: PORTABILITY, PR: WAITING FOR REVIEW

#5743 `OPAMSWITCH` and `OPAMROOT` reverts
  master_changes.md
  src/client/opamConfigCommand.ml
  tests/reftests/switch-set.test
Labels: PR: QUEUED, PR: WAITING FOR REVIEW

#5718 Git on windows: check and advertise to use Git for Windows
  .github/workflows/main.yml
  master_changes.md
  src/client/opamAction.ml
  src/client/opamArg.ml
  src/client/opamClient.ml
  src/client/opamClient.mli
  src/client/opamClientConfig.mli
  src/client/opamCommands.ml
  src/client/opamConfigCommand.ml
  src/core/opamCoreConfig.ml
  src/core/opamCoreConfig.mli
  src/core/opamProcess.ml
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/core/opamSystem.ml
  src/core/opamSystem.mli
  src/format/opamFile.ml
  src/format/opamFile.mli
  tests/reftests/var-option.test
Labels: AREA: PORTABILITY, PR: WAITING FOR REVIEW, CI:BINARIES

#5779 Release 2.2.0~beta1
  .github/workflows/ci.ml
  .github/workflows/main.yml
  CHANGES
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
  opam.opam
  tests/reftests/swhid.unix.test
Labels: STATE: READY TO MERGE

#5780 Fix macos sandbox script incorrectly assuming that `getconf` doesn't exist
  master_changes.md
  src/state/shellscripts/sandbox_exec.sh
Labels: AREA: SANDBOX, STATE: READY TO MERGE

#5785 Bump the version number after the release of 2.2.0~beta1
  .github/scripts/main/solvers.sh
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
  opam.opam
Labels: STATE: READY TO MERGE

#5808 Install rsync to the internal Cygwin installation
  master_changes.md
  src/client/opamInitDefaults.ml
  src/state/opamSysInteract.ml
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#5812 fix typo in doc of opam lint --recursive
  master_changes.md
  src/client/opamArg.ml
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE
