Repository ocaml/opam, pull requests merged in 2024-10, with the labels that each got.

#6226 Documentation: Update the command to install opam to point to the new simplified url on opam.ocaml.org
  doc/pages/Install.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6229 [2.3] Reftest: add more exhaustive pin command test
  master_changes.md
  tests/reftests/dune.inc
  tests/reftests/pin-legacy.test
  tests/reftests/pin.test
Labels: AREA:TEST, STATE: READY TO MERGE

#6221 Pin: fix first local vcs fetch rsyncing all source
  master_changes.md
  src/client/opamPinCommand.ml
  tests/reftests/fetch-package.test
  tests/reftests/pin.test
  tests/reftests/rec-pin.test
Labels: KIND: BUG

#6222 [2.3] Pin: fix first local vcs fetch rsyncing all source
  master_changes.md
  src/client/opamPinCommand.ml
  tests/reftests/fetch-package.test
  tests/reftests/pin.test
  tests/reftests/rec-pin.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6223 Update the vendored dependencies and unlock OCaml 5.3 compatibility
  master_changes.md
  src_ext/Makefile.dune
  src_ext/Makefile.sources
  tests/reftests/repository.test
Labels: AREA: BUILD, STATE: READY TO MERGE

#6216 Fix the compilation of opam on Windows with OCaml >= 5.0 (again)
  .github/scripts/main/create-ocaml-cache.sh
  .github/scripts/main/main.sh
  .github/scripts/main/ocaml-cache.sh
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  src/core/dune
  src/core/opamStubs.ocaml4.ml
  src/core/opamStubs.ocaml5.ml
  src/core/opamWin32Stubs.win32.ml
Labels: AREA: PORTABILITY, AREA: BUILD, STATE: READY TO MERGE

#6225 [2.3 backport] Update the vendored dependencies and unlock OCaml 5.3 compatibility
  master_changes.md
  src_ext/Makefile.dune
  src_ext/Makefile.sources
  tests/reftests/repository.test
Labels: AREA: BUILD

#6224 [2.3 backport] Fix the compilation of opam on Windows with OCaml >= 5.0 (again)
  .github/scripts/main/create-ocaml-cache.sh
  .github/scripts/main/main.sh
  .github/scripts/main/ocaml-cache.sh
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  src/core/dune
  src/core/opamStubs.ocaml4.ml
  src/core/opamStubs.ocaml5.ml
  src/core/opamWin32Stubs.win32.ml
Labels: AREA: PORTABILITY, AREA: BUILD, STATE: READY TO MERGE

#6230 System polling: Harden the process calls to account for failure
  master_changes.md
  src/core/opamStd.ml
Labels: AREA: PORTABILITY

#6228 [2.3 backport] System polling: Harden the process calls to account for failure
  master_changes.md
  src/core/opamStd.ml
Labels: KIND: BUG, AREA: PORTABILITY

#6231 Fix debian manual url fragment
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6233 Reftest: add `opam-cache` printing command
  master_changes.md
  src/state/opamSwitchState.mli
  tests/reftests/dune
  tests/reftests/readme.md
  tests/reftests/reftests.test
  tests/reftests/run.ml
Labels: AREA:TEST, STATE: READY TO MERGE

#6234 [2.3] Reftest: add opam-cache printing command
  master_changes.md
  src/state/opamSwitchState.mli
  tests/reftests/dune
  tests/reftests/readme.md
  tests/reftests/reftests.test
  tests/reftests/run.ml
Labels: AREA:TEST

#6213 Fix the install cache storing the wrong version of the opam file after a build failure
  master_changes.md
  src/client/opamSolution.ml
  tests/reftests/cache.test
  tests/reftests/dune.inc
Labels: KIND: BUG, AREA: ENGINE

#6219 Fix lint W59 with a local path that is not an archive
  master_changes.md
  src/core/opamSystem.ml
  src/core/opamSystem.mli
  src/state/opamFileTools.ml
  tests/reftests/lint.test
  tests/reftests/pin.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6236 Release 2.3.0~beta1
  CHANGES
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: STATE: READY TO MERGE, AREA: RELEASE

#6238 install scripts: add 2.3.0-beta1 binaries
  master_changes.md
  shell/install.ps1
  shell/install.sh
Labels: AREA: RELEASE

#6240 [2.3] Bump the version to 2.3.0~beta2~dev
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: AREA: RELEASE

#6244 Fix the detection of the current terminal size
  master_changes.md
  src/core/dune
  src/core/opamCommonStubs.c
  src/core/opamStd.ml
  src/core/opamStubs.mli
  src/core/opamStubs.unix.ml
  src/core/opamUnix.c
  src/core/opamWin32Stubs.win32.ml
Labels: KIND: BUG, AREA: UI

#6246 [2.3 backport] Fix the detection of the current terminal size
  master_changes.md
  src/core/dune
  src/core/opamCommonStubs.c
  src/core/opamStd.ml
  src/core/opamStubs.mli
  src/core/opamStubs.unix.ml
  src/core/opamUnix.c
  src/core/opamWin32Stubs.win32.ml
Labels: KIND: BUG, AREA: UI, STATE: READY TO MERGE

#5349 GHA: add doc job
  .github/scripts/main/main.sh
  .github/scripts/main/preamble.sh
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
Labels: AREA: DOCUMENTATION, AREA:TEST, PR: WAITING FOR REVIEW

#6150 Some ocaml doc fixes
  master_changes.md
  src/client/opamAction.mli
  src/client/opamArg.mli
  src/client/opamArgTools.mli
  src/client/opamAuxCommands.mli
  src/client/opamCLIVersion.mli
  src/client/opamCliMain.mli
  src/client/opamClient.mli
  src/client/opamConfigCommand.mli
  src/client/opamPinCommand.mli
  src/client/opamRepositoryCommand.mli
  src/core/opamFilename.mli
  src/core/opamHash.mli
  src/core/opamParallel.mli
  src/core/opamProcess.mli
  src/core/opamStd.mli
  src/core/opamStubs.mli
  src/core/opamSystem.mli
  src/core/opamVersionCompare.mli
  src/format/opamFile.mli
  src/format/opamFilter.mli
  src/format/opamFormat.mli
  src/format/opamFormula.mli
  src/format/opamPackage.mli
  src/format/opamPath.mli
  src/format/opamPp.mli
  src/format/opamSwitch.mli
  src/format/opamTypes.mli
  src/format/opamTypesBase.mli
  src/repository/opamDarcs.mli
  src/repository/opamDownload.mli
  src/repository/opamGit.mli
  src/repository/opamHg.mli
  src/repository/opamRepository.mli
  src/repository/opamRepositoryBackend.mli
  src/repository/opamVCS.mli
  src/solver/opamCudf.mli
  src/solver/opamCudfSolver.mli
  src/solver/opamSolver.mli
  src/state/opamEnv.mli
  src/state/opamFileTools.mli
  src/state/opamFormatUpgrade.mli
  src/state/opamPackageVar.mli
  src/state/opamRepositoryState.mli
  src/state/opamStateConfig.mli
  src/state/opamStateTypes.mli
  src/state/opamSwitchState.mli
  src/state/opamSysInteract.mli
  src/state/opamUpdate.mli
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#6237 [2.3] Release script improvements after 2.3.0~beta1
  doc/pages/Install.md
  master_changes.md
  release/Dockerfile.in
  release/Makefile
  release/readme.md
  release/release.sh
Labels: AREA: RELEASE

#6242 Release script improvements after 2.3.0~beta1
  doc/pages/Install.md
  master_changes.md
  release/Dockerfile.in
  release/Makefile
  release/readme.md
  release/release.sh
Labels: AREA: RELEASE

#6257 Release 2.3.0~beta2
  CHANGES
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: AREA: RELEASE

#6258 [2.3] Release script: Add NetBSD/x86_64 to the build matrix
  release/Makefile
  release/release.sh
Labels: AREA: PORTABILITY, AREA: RELEASE

#6259 Release script: Add NetBSD/x86_64 to the build matrix
  release/Makefile
  release/release.sh
Labels: AREA: PORTABILITY, AREA: RELEASE

#6262 Add opam 2.3.0~beta2 to the install scripts
  master_changes.md
  shell/install.ps1
  shell/install.sh
Labels: AREA: RELEASE

#6265 [2.3] Bump the version to 2.3.0~beta3~dev
  configure
  configure.ac
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: AREA: RELEASE

#6264 Reorder the release steps
  release/readme.md
  release/windows.md
Labels: AREA: RELEASE

#6267 fix a typo in the man page
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#6197 Add an admin command to compare 2 package versions (named operators)
  doc/man/opam-admin-topics.inc
  master_changes.md
  src/client/opamAdminCommand.ml
  src/format/opamFormula.ml
  src/format/opamFormula.mli
  tests/reftests/admin.test
Labels: AREA: UI, STATE: READY TO MERGE

#6266 [2.3 backport] Reorder the release steps
  release/readme.md
  release/windows.md
Labels: AREA: RELEASE

#6251 Doc: point users to ways to override the default opam root location in the opam init manpage
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#6272 Improve the messages when a package is not up-to-date on opam upgrade
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/avoid-version.test
  tests/reftests/deprecated.test
  tests/reftests/init.test
  tests/reftests/install-formula.test
  tests/reftests/switch-invariant.test
  tests/reftests/upgrade-two-point-o.test
Labels: AREA: UI

#6279 Release 2.3.0~rc1
  CHANGES
  configure
  configure.ac
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
  release/readme.md
Labels: STATE: READY TO MERGE, AREA: RELEASE

#6282 Add 2.3.0~rc1 to the install scripts
  master_changes.md
  shell/install.ps1
  shell/install.sh
Labels: AREA: RELEASE
