Repository ocaml/opam, pull requests merged in 2024-05, with the labels that each got.

#5912 Fix rounding error when displaying the timestamp in debug mode
  master_changes.md
  src/core/opamConsole.ml
Labels: KIND: BUG, STATE: READY TO MERGE

#5909 Benchmark opam install --deps-only of an already installed package
  master_changes.md
  tests/bench/bench.ml
Labels: AREA:TEST, STATE: READY TO MERGE, AREA: PERFORMANCE

#5919 Fix opam tree --test --doc assigning the with-{test,doc} variables to unrequested packages
  master_changes.md
  src/client/opamTreeCommand.ml
  tests/reftests/tree.test
Labels: AREA: ENGINE, PR: WAITING FOR REVIEW

#5943 Allow to parse opam 2.1 switch import files containing extra-files
  master_changes.md
  src/client/opamSwitchCommand.ml
  tests/reftests/switch-import.test
Labels: KIND: BUG, PR: WAITING FOR REVIEW

#5904 Reset the "jobs" config variable when upgrading to opam 2.2
  master_changes.md
  src/format/opamFile.ml
  src/state/opamFormatUpgrade.ml
  tests/reftests/init-ocaml-eval-variables.unix.test
  tests/reftests/init-ocaml-eval-variables.win32.test
  tests/reftests/opamroot-versions.test
Labels: STATE: READY TO MERGE

#5921 Fix downloading URLs with invalid characters
  master_changes.md
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/repository/opamDownload.ml
Labels: KIND: BUG, AREA: REPOSITORY, PR: WAITING FOR REVIEW

#5908 Fix performance regression when calling opam install --deps-only on an already installed package
  master_changes.md
  src/client/opamClient.ml
Labels: AREA: ENGINE, STATE: READY TO MERGE, AREA: PERFORMANCE

#5935 Fixes to reversal of environment updates
  master_changes.md
  src/core/opamStd.ml
  src/core/opamStd.mli
  src/state/opamEnv.ml
  tests/reftests/env.test
  tests/reftests/env.unix.test
  tests/reftests/env.win32.test
  tests/reftests/run.ml
Labels: KIND: BUG, STATE: READY TO MERGE

#5953 Mitigate copying/deletion of unrecognised symlinks
  master_changes.md
  src/core/opamSystem.ml
Labels: AREA: PORTABILITY, STATE: READY TO MERGE

#5959 Update shell/install.sh for opam 2.1.6
  shell/install.sh
Labels: AREA: RELEASE

#5957 Release script fixes and improvements
  release/Dockerfile.in
  release/Makefile
  release/readme.md
Labels: AREA: RELEASE

#5961 Fix opamfile package var typo
  master_changes.md
  src/state/opamPackageVar.ml
  tests/reftests/var-option.test
Labels: AREA: UI, STATE: READY TO MERGE

#5964 Tweak incorrect case in `--cygwin-extra-packages`
  master_changes.md
  src/client/opamCommands.ml
Labels: KIND: BUG, PR: WAITING FOR REVIEW, KIND: REGRESSION

#5962 Move last-env `OPAM_LAST_ENV` files outside the switch
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamConfigCommand.ml
  src/format/opamFile.ml
  src/format/opamPath.ml
  src/format/opamPath.mli
  tests/reftests/clean.test
  tests/reftests/env.test
Labels: AREA: ENGINE, STATE: READY TO MERGE

#5970 UTF-8 paged --help on Windows
  master_changes.md
  src/client/opamCliMain.ml
  src/core/opamStubs.dummy.ml
  src/core/opamStubs.mli
  src/stubs/win32/opamWin32Stubs.ml
  src/stubs/win32/opamWindows.c
  src_ext/Makefile.sources
Labels: AREA: PORTABILITY

#5927 Relax warning 41 for package variables guarded by a :installed filter
  master_changes.md
  src/format/opamFilter.mli
  src/format/opamFormula.ml
  src/format/opamFormula.mli
  src/state/opamFileTools.ml
  tests/reftests/lint.test
Labels: STATE: READY TO MERGE
