Repository ocaml/opam, pull requests merged in 2024-07, with the labels that each got.

#5980 Bump opam-root-version to 2.2
  master_changes.md
  release/readme.md
  src/format/opamFile.ml
  src/state/opamFormatUpgrade.ml
  tests/reftests/opamroot-versions.test
Labels: AREA: RELEASE

#6047 Restore signature of OpamStateConfig.opamroot
  master_changes.md
  src/client/opamCliMain.ml
  src/client/opamClientConfig.ml
  src/client/opamCommands.ml
  src/state/opamStateConfig.ml
  src/state/opamStateConfig.mli
Labels: AREA: API

#5989 Avoid head -c GNUism in reftests
  master_changes.md
  tests/reftests/legacy-git.test
  tests/reftests/legacy-local.test
Labels: AREA:TEST, STATE: READY TO MERGE

#6034 Suppress Windows-specific menus with `opam init -ya`
  master_changes.md
  src/client/opamClient.ml
Labels: AREA: UI, STATE: READY TO MERGE

#6055 Package name encoding in conflict message
  master_changes.md
  src/solver/opamCudf.ml
  tests/reftests/dune.inc
  tests/reftests/empty-conflicts-007.test
Labels: AREA: UI, STATE: READY TO MERGE

#6066 release: Fix the creation of the opam-full-<version>.tar.gz archive
  master_changes.md
  release/Makefile
  src_ext/Makefile
Labels: STATE: READY TO MERGE, AREA: RELEASE

#6067 [2.2 backport] release: Fix the creation of the opam-full-<version>.tar.gz archive
  master_changes.md
  release/Makefile
  src_ext/Makefile
Labels: AREA: RELEASE

#5988 Documentation: remove the ppa from the installation instructions on Ubuntu
  doc/pages/Install.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6079 GHA: Several fixes on depexts workflow
  .github/scripts/depexts/generate-actions.sh
  master_changes.md
Labels: AREA:TEST, AREA: DEPEXTS

#5642 reftests: add test for operators in opamfile filters
  master_changes.md
  tests/reftests/dune.inc
  tests/reftests/filter-operators.test
Labels: AREA:TEST, STATE: READY TO MERGE

#5327 reftests: updates on init test
  master_changes.md
  tests/reftests/dune.inc
  tests/reftests/init.test
Labels: AREA:TEST, STATE: READY TO MERGE

#6084 Remove opam 2.1 support from the release script
  master_changes.md
  release/Dockerfile.in
  release/Makefile
  release/readme.md
Labels: STATE: READY TO MERGE, AREA: RELEASE

#6085 [2.2 backport] Remove opam 2.1 support from the release script
  master_changes.md
  release/Dockerfile.in
  release/Makefile
  release/readme.md
Labels: AREA: RELEASE

#6054 depext: fix Debian/apt lookup for installed packages
  master_changes.md
  src/state/opamSysInteract.ml
Labels: AREA: DEPEXTS

#6083 [2.0 backport] Port the release script from master
  release/Dockerfile.in
  release/Makefile
  release/readme.md
  release/release.sh
  release/sign.sh
Labels: AREA: RELEASE

#6082 [2.1 backport] Port the release script from master
  release/Dockerfile.in
  release/Makefile
  release/readme.md
  release/release.sh
  release/sign.sh
Labels: AREA: RELEASE

#6086 [2.2] GHA: Several fixes on depexts workflow
  .github/scripts/depexts/generate-actions.sh
  master_changes.md
Labels: AREA:TEST, AREA: DEPEXTS, STATE: READY TO MERGE

#6104 Add support for wget2
  master_changes.md
  src/repository/opamDownload.ml
  tests/reftests/download.test
Labels: KIND: BUG

#6103 admin hashes cache: move under opam root
  master_changes.md
  src/client/opamAdminCommand.ml
  tests/reftests/admin.test
Labels: STATE: READY TO MERGE

#6068 Add every listed checksums of a given archive to the cache when fetching from it
  .github/scripts/cygwin.cmd
  master_changes.md
  src/client/opamAdminCommand.ml
  src/repository/opamRepository.ml
  src/repository/opamRepository.mli
  tests/reftests/admin-cache.test
  tests/reftests/admin.test
  tests/reftests/archive.test
  tests/reftests/dune.inc
  tests/reftests/extrasource.test
Labels: AREA: ENGINE, STATE: READY TO MERGE

#6094 Make the benchmark setup process faster and the benchmark itself more stable
  bench.Dockerfile
  master_changes.md
  tests/bench/bench.ml
Labels: AREA:TEST

#6102 Stop using polymorphic comparison when comparing switch_selections
  master_changes.md
  src/format/opamTypesBase.ml
  src/format/opamTypesBase.mli
  src/state/opamSwitchAction.ml
  src/state/opamUpdate.ml
Labels: STATE: READY TO MERGE

#6078 Add a benchmark showing the current performance of OpamVersionCompare
  bench.Dockerfile
  master_changes.md
  tests/bench/bench.ml
  tests/bench/dune
Labels: AREA:TEST, AREA: PERFORMANCE

#5624 Ensure all archives are retrieved in `make cache-archives`
  master_changes.md
  src_ext/Makefile
Labels: STATE: READY TO MERGE

#5534 Unset OPAM_SWITCH_PREFIX when using make cold
  Makefile
  master_changes.md
Labels: AREA: BUILD, STATE: READY TO MERGE

#5377 Reftest: add `build-env` overwrite predefined build env opam vars
  master_changes.md
  tests/reftests/env.test
Labels: STATE: READY TO MERGE

#5388 Add dependencies only switch import
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamSwitchCommand.ml
  src/client/opamSwitchCommand.mli
  tests/reftests/switch-import.test
Labels: STATE: READY TO MERGE

#5474 test: add sources directory cleaning test
  master_changes.md
  tests/reftests/clean.test
Labels: AREA:TEST, STATE: READY TO MERGE

#6116 Always list all the repositories in 'opam config report' regardless of whether or not a switch is currently set
  master_changes.md
  src/client/opamCommands.ml
  tests/reftests/config.test
Labels: AREA: UI

#5946 doc: fix pinning instruction in readme
  README.md
  master_changes.md
Labels: AREA: DOCUMENTATION, STATE: READY TO MERGE

#5682 Add a verbose-on option.
  master_changes.md
  src/client/opamAction.ml
  src/client/opamArg.ml
  src/client/opamClientConfig.ml
  src/client/opamClientConfig.mli
  src/core/opamStd.ml
  src/core/opamStd.mli
  tests/reftests/dune.inc
  tests/reftests/verbose-on.test
Labels: STATE: READY TO MERGE

#6119 doc: add brief note about version ordering and OCaml REPL example
  README.md
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6115 Remove the meta opam packages opam and opam-admin
  dune-project
  master_changes.md
  opam-admin.opam
  opam.opam
Labels: PR: WAITING FOR REVIEW

#6125 Fix regression: deps-only setting direct dependencies as root packages by default
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/deps-only.test
Labels: KIND: BUG, STATE: READY TO MERGE
