Repository ocaml/opam, pull requests merged in 2025-08, with the labels that each got.

#6596 doc: mention the compare-versions command in the manual
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6631 Improve the opam pin man page by being more explicit about which arguments are optional
  master_changes.md
  src/client/opamCommands.ml
Labels: AREA: DOCUMENTATION

#6638 Invalid character in package name should explain why
  master_changes.md
  src/format/opamPackage.ml
  tests/reftests/show.test
Labels: AREA: UI

#6650 Fix URL to Software Heritage
  doc/pages/Usage.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6640 Handle non-displayable characters when detecting an erroneous package name or version
  master_changes.md
  src/format/opamFormula.ml
  src/format/opamPackage.ml
  tests/reftests/show.test
Labels: AREA: UI

#6652 GHA: Fix the nixos depexts tests
  .github/scripts/depexts/generate-actions.sh
  master_changes.md
Labels: AREA:TEST

#6648 GHA: Ensure every part of the scripts are run with 'set -ue'
  .github/scripts/common/hygiene-preamble.sh
  .github/scripts/common/preamble.sh
  .github/scripts/depexts/generate-actions.sh
  .github/scripts/main/main.sh
  .github/scripts/main/preamble.sh
  .github/scripts/main/upgrade.sh
  master_changes.md
Labels: AREA:TEST, STATE: READY TO MERGE

#6582 GHA: Only run the get-changed-files action when in a PR
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
Labels: AREA:TEST, STATE: READY TO MERGE

#6394 GHA: add a job that test opam libs dependencies compilation
  .github/scripts/main/main.sh
  .github/scripts/main/preamble.sh
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
  release/readme.md
Labels: AREA:TEST, STATE: READY TO MERGE

#6417 Complete format upgrade mechanism at repo & switch level
  master_changes.md
  src/state/opamFormatUpgrade.ml
  src/state/opamFormatUpgrade.mli
  src/state/opamRepositoryState.ml
  src/state/opamSwitchState.ml
  tests/reftests/opamroot-versions.test
Labels: STATE: READY TO MERGE

#6656 GHA: Fix macOS builds by installing rsync
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
Labels: AREA:TEST

#6655 GHA: reverse dependencies job follow-up
  .github/scripts/main/main.sh
  master_changes.md
Labels: AREA: TEST

#6663 Update the dependency constraint on patch to now require its stable version
  .github/workflows/ci.ml
  .github/workflows/depexts.yml
  .github/workflows/main.yml
  master_changes.md
  opam-core.opam
  opam-repository.opam
Labels: AREA: BUILD, STATE: READY TO MERGE

#6658 OpamLocal.rsync_* doesn't use its return value
  master_changes.md
  src/repository/opamLocal.ml
  src/repository/opamLocal.mli
  src/repository/opamRepository.ml
  src/repository/opamVCS.ml
  src/state/opamFileTools.ml
Labels: IMPORTANT, AREA: API
