Repository ocaml/opam, pull requests merged in 2025-04, with the labels that each got.

#6436 Do not keep the build directory of the pinned packages
  master_changes.md
  src/client/opamSolution.ml
  tests/reftests/dune.inc
  tests/reftests/keep-build-dir.test
Labels: STATE: READY TO MERGE

#6166 reftest: add admin filter test
  master_changes.md
  tests/reftests/admin.test
Labels: AREA:TEST, STATE: READY TO MERGE

#6209 Fix opam install on a local directory not updating pinned packages' metadata
  master_changes.md
  src/client/opamAuxCommands.ml
  src/client/opamClient.ml
  src/format/opamFile.ml
  tests/reftests/pin.test
  tests/reftests/show.test
  tests/reftests/working-dir.test
Labels: KIND: BUG, AREA: ENGINE, IMPORTANT, STATE: READY TO MERGE

#6198 Fix empty updates in dynamic init scripts
  master_changes.md
  src/state/opamEnv.ml
  tests/reftests/dune.inc
  tests/reftests/variables-sh.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6319 Fail when trying to pin a package whose definition could not be found instead of forcing interactive edition
  master_changes.md
  src/client/opamPinCommand.ml
  tests/reftests/pin.test
Labels: STATE: READY TO MERGE

#6467 Only download Cygwin's setup.exe when the command is actually going to be displayed or used
  master_changes.md
  src/client/opamSolution.ml
  src/state/opamSysInteract.ml
  src/state/opamSysInteract.mli
Labels: AREA: PORTABILITY, AREA:TEST, STATE: READY TO MERGE

#6464 Disable the detection of available system packages on SUSE-based distributions
  master_changes.md
  src/state/opamSysInteract.ml
Labels: AREA: DEPEXTS, STATE: READY TO MERGE

#6470 Don't suggest setting the `nodosfilewarning` option of `CYGWIN`
  README.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6469 GHA: Restore the OCaml cache for the Windows jobs
  .github/scripts/main/ocaml-cache.sh
  .github/workflows/ci.ml
  .github/workflows/main.yml
  master_changes.md
Labels: AREA:TEST, STATE: READY TO MERGE

#6473 Release 2.4.0~alpha1
  CHANGES
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: STATE: READY TO MERGE, AREA: RELEASE

#6475 Add 2.4.0~alpha1 to the install scripts
  master_changes.md
  shell/install.ps1
  shell/install.sh
Labels: AREA: RELEASE

#6476 Bump the version number to 2.4.0~alpha2~dev
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: STATE: READY TO MERGE, AREA: RELEASE

#6485 Fix a memory leak by removing OPAMSTATS
  master_changes.md
  src/client/opamArg.ml
  src/client/opamCliMain.ml
  src/client/opamClientConfig.ml
  src/client/opamClientConfig.mli
  src/core/opamSystem.ml
  src/core/opamSystem.mli
  src/format/opamFile.ml
  src/format/opamFile.mli
Labels: STATE: READY TO MERGE, AREA: PERFORMANCE
