Repository ocaml/opam, pull requests merged in 2025-01, with the labels that each got.

#6361 Docs: Fix broken link to non-existing community repo
  doc/pages/Install.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6363 GHA: Fix the alpine depexts test + speedup gentoo
  .github/scripts/depexts/generate-actions.sh
  .github/workflows/depexts.yml
  master_changes.md
Labels: AREA:TEST

#6362 depext: relax OpenBSD lookup for installed packages
  master_changes.md
  src/state/opamSysInteract.ml
Labels: KIND: BUG, AREA: DEPEXTS, STATE: READY TO MERGE

#6324 Speedup the detection of available system packages with pacman and brew
  master_changes.md
  src/state/opamSysInteract.ml
Labels: STATE: READY TO MERGE, AREA: PERFORMANCE

#6370 Upgrade the vendored spdx_licenses to 1.3.0
  master_changes.md
  src_ext/Makefile.sources
Labels: AREA: BUILD

#6358 Display the version number of packages flagged with avoid-version/deprecated gray
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamListCommand.ml
  src/core/opamConsole.ml
  src/core/opamConsole.mli
Labels: AREA: UI, STATE: READY TO MERGE

#6192 GHA: Add OCaml 5.3 to the build matrix
  .github/scripts/main/ocaml-cache.sh
  .github/workflows/ci.ml
  .github/workflows/lib.ml
  .github/workflows/main.yml
  master_changes.md
  src_ext/Makefile.dune
  src_ext/Makefile.sources
Labels: AREA: PORTABILITY, AREA: BUILD, AREA:TEST, STATE: READY TO MERGE

#5663 GHA: Make sure opam init works in the absence of OPAMROOT
  .github/scripts/main/test.sh
  master_changes.md
Labels: AREA:TEST
