Repository ocaml/opam, pull requests merged in 2025-03, with the labels that each got.

#6401 Display Windows `NTSTATUS` exit codes in hex
  master_changes.md
  src/core/opamProcess.ml
Labels: AREA: PORTABILITY

#6411 lock: add '--keep-local' argument to add local pins to 'pin-depends:' field
  master_changes.md
  src/client/opamCommands.ml
  src/client/opamLockCommand.ml
  src/client/opamLockCommand.mli
  tests/reftests/lock.test
Labels: STATE: READY TO MERGE

#6256 Ensure the right versions of packages are used when simulating pinning
  master_changes.md
  src/client/opamAuxCommands.ml
  tests/reftests/pin.test
Labels: KIND: BUG, AREA: ENGINE, IMPORTANT, STATE: READY TO MERGE

#6420 Change the type returned by `OpamRepository.revision` from version to string
  master_changes.md
  src/client/opamAction.ml
  src/client/opamAdminCommand.ml
  src/client/opamListCommand.ml
  src/client/opamPinCommand.ml
  src/client/opamSwitchCommand.ml
  src/repository/opamRepository.mli
  src/repository/opamRepositoryBackend.ml
  src/repository/opamRepositoryBackend.mli
  src/repository/opamVCS.ml
Labels: STATE: READY TO MERGE, AREA: API

#6412 reftest: untie lock test from OPAMEDITOR hack, and fix lock VCS remote detection
  master_changes.md
  tests/reftests/lock.test
Labels: AREA:TEST

#5892 Replace every use of GNU Patch by the OCaml patch library
  .github/workflows/ci.ml
  .github/workflows/main.yml
  configure
  configure.ac
  master_changes.md
  opam-core.opam
  opam-repository.opam
  src/client/opamAction.ml
  src/client/opamAction.mli
  src/client/opamInitDefaults.ml
  src/core/dune
  src/core/opamFilename.ml
  src/core/opamFilename.mli
  src/core/opamSystem.ml
  src/core/opamSystem.mli
  src/repository/dune
  src/repository/opamHTTP.ml
  src/repository/opamLocal.ml
  src/repository/opamRepository.ml
  src/repository/opamRepositoryBackend.ml
  src/repository/opamRepositoryBackend.mli
  src_ext/Makefile
  src_ext/Makefile.sources
  tests/lib/dune
  tests/lib/patchDiff.expected
  tests/lib/patchDiff.ml
  tests/reftests/repository.test
  tests/reftests/update.test
Labels: IMPORTANT, STATE: READY TO MERGE

#6439 Fix archive retrieval when a subpath is specified
  master_changes.md
  src/repository/opamLocal.ml
  tests/reftests/rec-pin.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6444 GHA: Unbreak the depexts workflow by updating the opam-repository hash
  .github/workflows/depexts.yml
  master_changes.md
Labels: AREA:TEST

#6443 Upgrade the benchmark's base image to Debian 12
  bench.Dockerfile
  master_changes.md
Labels: AREA:TEST

#6447 GHA: Enable the depexts workflow on master and when the opam description change
  .github/workflows/depexts.yml
  master_changes.md
Labels: AREA:TEST
