Repository ocaml/opam, pull requests merged in 2025-06, with the labels that each got.

#6530 `opam install . --deps-only` comply with the real constraints of packages
  master_changes.md
  src/client/opamAuxCommands.ml
  src/state/opamStateTypes.mli
  src/state/opamSwitchState.ml
  tests/reftests/dune.inc
  tests/reftests/pin.test
  tests/reftests/simulated-pin.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6522 Fix simulated pinned packages reinstall trigger
  master_changes.md
  src/client/opamAuxCommands.ml
  tests/reftests/simulated-pin.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6538 Release: Call the opam configure script with on Windows
  master_changes.md
  release/Makefile
Labels: AREA: RELEASE

#6544 Fix opam install --deps-only using the opam description of the wrong package in some cases
  master_changes.md
  src/client/opamClient.ml
  src/state/opamSwitchState.ml
  tests/reftests/deps-only.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6539 reftest: add test for opam repo ci reinstall workflow
  master_changes.md
  tests/reftests/dune.inc
  tests/reftests/opam-repo-ci.test
Labels: AREA:TEST, STATE: READY TO MERGE

#6550 No longer remove source dir on reinstall
  master_changes.md
  src/client/opamAction.ml
  tests/reftests/action-disk.test
  tests/reftests/clean.test
  tests/reftests/dune.inc
  tests/reftests/opam-repo-ci.test
  tests/reftests/run.ml
  tests/reftests/sources-directory-cleaning.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6555 Release 2.4.0~beta1
  CHANGES
  configure
  configure.ac
  master_changes.md
  opam-client.opam
  opam-core.opam
  opam-devel.opam
  opam-format.opam
  opam-installer.opam
  opam-repository.opam
  opam-solver.opam
  opam-state.opam
Labels: AREA: RELEASE

#6559 Add opam 2.4.0~beta1 to the install scripts
  master_changes.md
  shell/install.ps1
  shell/install.sh
Labels: AREA: RELEASE

#6573 GHA: gawk was re-added to the base fedora images
  .github/scripts/depexts/generate-actions.sh
  master_changes.md
Labels: AREA:TEST

#6571 on `opam switch create <version>`, use avoid-version compiler if it is the only one available
  master_changes.md
  src/client/opamSwitchCommand.ml
  tests/reftests/switch-creation.test
Labels: KIND: BUG, STATE: READY TO MERGE
