Repository ocaml/opam, pull requests merged in 2025-09, with the labels that each got.

#6661 Add OpamHash.check_string
  master_changes.md
  src/client/opamSwitchCommand.ml
  src/core/opamHash.ml
  src/core/opamHash.mli
Labels: IMPORTANT, AREA: API

#6688 Add a test showing the behaviour of opam tree on local packages that happen to be already pinned
  master_changes.md
  tests/reftests/tree.test
Labels: AREA: TEST, STATE: READY TO MERGE

#6691 Add a test showing the behaviour of version pins when one of the dependencies isn't up-to-date
  master_changes.md
  tests/reftests/pin.test
Labels: AREA: TEST

#6696 Pretty printing of some error for opam source & build actions
  master_changes.md
  src/client/opamAction.ml
  src/client/opamCommands.ml
  tests/reftests/extrafile.test
  tests/reftests/extrasource.test
Labels: AREA: UI, STATE: READY TO MERGE

#6700 Update all the download-if-missing dependencies to their latest version
  .gitignore
  master_changes.md
  src_ext/Makefile
  src_ext/Makefile.dune
  src_ext/Makefile.sources
  src_ext/patches/re/0001-Backport-to-OCaml-4.12.patch
  src_ext/patches/re/0002-Backport-to-OCaml-4.08.patch
Labels: AREA: BUILD, STATE: READY TO MERGE

#6701 Simplify the src_ext/update-sources.sh script
  .github/scripts/main/hygiene.sh
  master_changes.md
  src_ext/update-sources.sh
Labels: AREA: TEST
