Repository ocaml/opam, pull requests merged in 2025-02, with the labels that each got.

#5627 Add an explanation of how plugins work to the manual
  doc/pages/Manual.md
  master_changes.md
Labels: AREA: DOCUMENTATION

#6309 Don't ask confirmation when pinning a new package
  master_changes.md
  src/client/opamPinCommand.ml
  tests/reftests/assume-built.test
  tests/reftests/autopin.test
  tests/reftests/config.test
  tests/reftests/conflict-resto.test
  tests/reftests/fetch-package.test
  tests/reftests/inplace.test
  tests/reftests/json.unix.test
  tests/reftests/list-large-dependencies.test
  tests/reftests/lock.test
  tests/reftests/pin-legacy.test
  tests/reftests/pin.test
  tests/reftests/rec-pin.test
  tests/reftests/switch-import.test
  tests/reftests/tree.test
  tests/reftests/update-upgrade.test
  tests/reftests/upgrade.test
  tests/reftests/working-dir.test
Labels: AREA: UI

#6378 Make sure download.test does not fail due to a checksum collision in the download cache
  master_changes.md
  tests/reftests/download.test
Labels: AREA:TEST, STATE: READY TO MERGE

#6273 opam upgrade: Do not show the not-up-to-date message with packages tagged with avoid-version
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/avoid-version.test
  tests/reftests/deprecated.test
  tests/reftests/upgrade.test
Labels: KIND: BUG, AREA: UI, STATE: READY TO MERGE

#5510 Add the OPAMSOLVERTOLERANCE environment variable to allow users to fix solver timeouts for good
  doc/pages/Tricks.md
  master_changes.md
  src/client/opamArg.ml
  src/client/opamClientConfig.mli
  src/solver/opamBuiltin0install.ml
  src/solver/opamBuiltinMccs.dummy.ml
  src/solver/opamBuiltinMccs.real.ml
  src/solver/opamBuiltinZ3.dummy.ml
  src/solver/opamBuiltinZ3.real.ml
  src/solver/opamCudf.ml
  src/solver/opamCudfSolver.ml
  src/solver/opamCudfSolverSig.ml
  src/solver/opamSolverConfig.ml
  src/solver/opamSolverConfig.mli
Labels: AREA: SOLVER

#6375 Do not ask to install pin-depends twice
  master_changes.md
  src/client/opamAuxCommands.ml
Labels: KIND: BUG, AREA: UI, STATE: READY TO MERGE

#6373 Fix regression on 'opam upgrade <package>' upgrading unrelated things
  master_changes.md
  src/client/opamClient.ml
  tests/reftests/upgrade.test
Labels: KIND: BUG, AREA: ENGINE, STATE: READY TO MERGE

#6376 Do not pre-write the answer to questions with the default anwser
  master_changes.md
  src/client/opamClient.ml
  src/client/opamSolution.ml
  src/core/opamConsole.ml
Labels: AREA: UI, STATE: READY TO MERGE

#6372 Improve the installation documentation
  doc/pages/Distribution.md
  doc/pages/Install.md
  doc/pages/index.menu
  master_changes.md
  release/readme.md
Labels: AREA: DOCUMENTATION

#6392 GHA: Avoid the broken diffutils 3.11 release
  .github/scripts/cygwin.cmd
Labels: AREA:TEST

#5488 [API] Make the ?lock_kind parameters non-optional to avoid breaking the library users after they upgrade their opam root
  master_changes.md
  src/client/opamListCommand.ml
  src/client/opamSwitchCommand.ml
  src/state/opamGlobalState.ml
  src/state/opamRepositoryState.ml
  src/state/opamStateConfig.ml
  src/state/opamStateConfig.mli
  src/state/opamSwitchState.ml
  src/state/opamSwitchState.mli
Labels: STATE: READY TO MERGE, AREA: API

#5471 lock: fix pin-depends with `with-` variables
  master_changes.md
  src/client/opamLockCommand.ml
  tests/reftests/lock.test
Labels: KIND: BUG, STATE: READY TO MERGE

#6317 lint: add W74 to detect 'pin-depends' packages that are not present in 'depends' nor in 'depopts'
  master_changes.md
  src/state/opamFileTools.ml
  tests/reftests/lint.test
Labels: STATE: READY TO MERGE, AREA: LINTER

#6307 Remove ocaml-system from the list of default compilers used during opam init
  master_changes.md
  src/client/opamInitDefaults.ml
  tests/reftests/init.test
Labels: AREA: PORTABILITY, AREA: UI, IMPORTANT
